/* Delivery Comandas — camada de aplicação */
"use strict";
const APP="dcv2:",OLD="comandasdelivery:",AUTH_KEY=APP+"auth:users",SESSION_KEY=APP+"auth:session",MIGRATION_KEY=APP+"migration:v3",$=s=>document.querySelector(s),pad=n=>String(n).padStart(2,"0"),today=()=>{const d=new Date();return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`},brl=n=>(Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),dateLabel=k=>{const[y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"})};
let user=localStorage.getItem(SESSION_KEY),view="day",day=today(),expDay=today(),month=new Date(new Date().getFullYear(),new Date().getMonth(),1),loginMode="login";
function safeJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw==null?fallback:JSON.parse(raw)}catch{return fallback}}
function userKey(k){return`${APP}${user}:${k}`}function load(k,f){return safeJSON(userKey(k),f)}function save(k,v){localStorage.setItem(userKey(k),JSON.stringify(v))}
const defaultDay=k=>({date:k,entries:[],arrancada:0,kmInicial:"",kmFinal:""}),defaultExp=k=>({date:k,items:[]}),defaultMech=()=>({ultimaTroca:"",intervalo:"",motoKm:""}),getDay=k=>load(`day:${k}`,defaultDay(k)),getExp=k=>load(`exp:${k}`,defaultExp(k)),getMech=()=>load("mechanica",defaultMech());
const authUsers=()=>safeJSON(AUTH_KEY,{}),setAuthUsers=v=>localStorage.setItem(AUTH_KEY,JSON.stringify(v));
function simpleHash(str){let h=0;for(let i=0;i<str.length;i++)h=(Math.imul(31,h)+str.charCodeAt(i))|0;return String(h)}
const passwordRecord=p=>({hash:simpleHash(p),encoded:btoa(unescape(encodeURIComponent(p)))});
function migrateLegacyData(){
 if(localStorage.getItem(MIGRATION_KEY))return;
 const oldUsers=safeJSON(OLD+"auth:users",{}),currentUsers=safeJSON(APP+"null:users",{}),discovered=new Set([...Object.keys(oldUsers),...Object.keys(currentUsers)]),legacyPrefix=OLD+"user:";
 for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||"";if(k.startsWith(legacyPrefix)){const rest=k.slice(legacyPrefix.length),p=rest.indexOf(":");if(p>0)discovered.add(rest.slice(0,p))}}
 const backup={createdAt:new Date().toISOString(),source:"comandasdelivery",users:{},currentV2Users:currentUsers,data:{}},targetUsers=authUsers();
 for(const u of discovered){
  if(currentUsers[u]&&!targetUsers[u])targetUsers[u]={...currentUsers[u]};
  if(oldUsers[u]){backup.users[u]=oldUsers[u];if(!targetUsers[u])targetUsers[u]={legacyHash:oldUsers[u].passwordHash||null,createdAt:oldUsers[u].createdAt||new Date().toISOString()};else if(!targetUsers[u].legacyHash&&oldUsers[u].passwordHash)targetUsers[u].legacyHash=oldUsers[u].passwordHash}
  const prefix=`${OLD}user:${u}:`,targetPrefix=`${APP}${u}:`;
  for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||"";if(!k.startsWith(prefix))continue;const suffix=k.slice(prefix.length),raw=localStorage.getItem(k);backup.data[`${u}:${suffix}`]=raw;if(localStorage.getItem(targetPrefix+suffix)!==null)continue;let value=raw;try{const parsed=JSON.parse(raw);if(suffix.startsWith("day:")&&parsed){parsed.entries=(parsed.entries||[]).map(e=>({...e,ok:e.ok===true||e.conferido===true}));delete parsed.conferido;parsed.kmInicial??="";parsed.kmFinal??="";value=JSON.stringify(parsed)}else if(suffix.startsWith("expense:")&&parsed){value=JSON.stringify({date:parsed.date||parsed.dateKey||suffix.slice(8),items:(parsed.items||[]).map(e=>({id:e.id||crypto.randomUUID(),cat:e.cat||e.categoria||"outros",desc:e.desc??e.descricao??"",val:e.val??e.valor??""}))})}}catch{}localStorage.setItem(targetPrefix+suffix.replace(/^expense:/,"exp:"),value)}
  const di=safeJSON(prefix+"day-index",[]);if(Array.isArray(di))localStorage.setItem(targetPrefix+"legacy-day-index",JSON.stringify(di));const ei=safeJSON(prefix+"expense-index",[]);if(Array.isArray(ei))localStorage.setItem(targetPrefix+"legacy-exp-index",JSON.stringify(ei));
 }
 setAuthUsers(targetUsers);try{localStorage.setItem(APP+"migration-backup:"+Date.now(),JSON.stringify(backup))}catch{}localStorage.setItem(MIGRATION_KEY,JSON.stringify({completedAt:new Date().toISOString(),users:[...discovered],version:3}));
 if(!user&&localStorage.getItem(OLD+"auth:session")){const oldSession=localStorage.getItem(OLD+"auth:session");if(targetUsers[oldSession]){user=oldSession;localStorage.setItem(SESSION_KEY,user)}}
}
migrateLegacyData();
function loginOk(u,p){const rec=authUsers()[u];if(!rec)return false;const e=passwordRecord(p).encoded;return(rec.encoded&&rec.encoded===e)||(rec.hash&&rec.hash===simpleHash(p))||(rec.passwordHash&&rec.passwordHash===simpleHash(p))||(rec.legacyHash&&rec.legacyHash===simpleHash(p))}
function register(u,p){u=(u||"").trim().toLowerCase();if(u.length<3||!p)return"Preencha usuário e senha (mínimo 3 caracteres).";const us=authUsers();if(us[u])return"Usuário já existe.";us[u]={...passwordRecord(p),createdAt:new Date().toISOString()};setAuthUsers(us);user=u;localStorage.setItem(SESSION_KEY,u);return""}
function doLogin(u,p){u=(u||"").trim().toLowerCase();if(!loginOk(u,p))return"Usuário ou senha inválidos.";user=u;localStorage.setItem(SESSION_KEY,u);return""}function logout(){localStorage.removeItem(SESSION_KEY);user=null;showLogin()}
function totals(d){const taxas=(d.entries||[]).reduce((s,e)=>s+(+e.taxa||0),0),km=(+d.kmFinal||0)-(+d.kmInicial||0);return{taxas,ent:(d.entries||[]).length,conf:(d.entries||[]).filter(e=>e.ok===true||e.conferido===true).length,arr:+d.arrancada||0,total:taxas+(+d.arrancada||0),km:km>0?km:0}}
function shell(content){document.body.innerHTML=`<div id="app"><header><div class="head"><div class="logo"></div><div><div class="brand">Delivery Comandas</div><div class="sub">${esc(user)}</div></div></div><div class="actions"><button class="ico" id="backup">⬇</button><button class="ico" id="logout">⏻</button></div></header><main>${content}</main><nav class="tabs">${tab("day","📋","Dia")}${tab("expenses","💸","Gastos")}${tab("mechanic","🔧","Mecânica")}${tab("month","📊","Mês")}</nav></div>`}
const tab=(v,i,t)=>`<button class="tab ${view===v?"active":""}" data-view="${v}"><b>${i}</b>${t}</button>`;
function renderDay(){const d=getDay(day),t=totals(d),rows=(d.entries||[]).map(e=>`<div class="entry" data-id="${esc(e.id)}"><input data-f="comanda" type="number" inputmode="numeric" placeholder="Nº" value="${esc(e.comanda||"")}"><input data-f="taxa" type="number" inputmode="decimal" placeholder="Taxa" value="${esc(e.taxa||"")}"><input class="check" data-f="ok" type="checkbox" ${e.ok||e.conferido?"checked":""}><button class="trash" data-remove>×</button></div>`).join("");return`<div class="daynav"><button class="navbtn" data-shift="-1">‹</button><div class="daycenter"><strong>${dateLabel(day)}</strong><input id="date" type="date" value="${day}"></div><button class="navbtn" data-shift="1">›</button></div><div class="card"><div class="title">Fechamento do dia</div><div class="kmgrid"><div><div class="small">KM inicial do dia</div><input id="kmi" type="number" inputmode="numeric" value="${esc(d.kmInicial)}" placeholder="Ex.: 45280"></div><div><div class="small">KM final do dia</div><input id="kmf" type="number" inputmode="numeric" value="${esc(d.kmFinal)}" placeholder="Ex.: 45397"></div></div><div class="kmresult"><span>Total rodado</span><b>${t.km} km</b></div></div><div class="card"><div class="row between"><div class="title">Comandas</div><span class="small">${t.conf}/${t.ent} conferidas</span></div><div class="tablehead"><span>Comanda</span><span>Taxa</span><span>OK</span><span></span></div>${rows||`<div class="empty">Nenhuma entrega lançada.<br>Toque em Nova comanda.</div>`}<button class="add" id="add">+ Nova comanda</button><div class="line"></div><div class="row between"><span>Arrancada do dia</span><div style="width:120px"><input id="arr" type="number" inputmode="decimal" value="${d.arrancada||0}"></div></div><div class="sum"><span>Entregas</span><b>${t.ent}</b></div><div class="sum"><span>Soma taxas</span><b>${brl(t.taxas)}</b></div><div class="sum"><span>Arrancada</span><b>${brl(t.arr)}</b></div><div class="sum total"><span>Total do dia</span><b>${brl(t.total)}</b></div></div>`}
function bindDay(){const d=getDay(day);$("#date").onchange=e=>{day=e.target.value;render()};["kmi","kmf","arr"].forEach(id=>$("#"+id).onchange=e=>{if(id==="kmi")d.kmInicial=e.target.value;if(id==="kmf")d.kmFinal=e.target.value;if(id==="arr")d.arrancada=e.target.value;save(`day:${day}`,d);render()});document.querySelectorAll(".entry").forEach(r=>{const id=r.dataset.id,e=d.entries.find(x=>x.id===id);r.querySelectorAll("input").forEach(i=>i.onchange=()=>{const f=i.dataset.f;if(f==="ok")e.ok=i.checked;else e[f]=i.value;delete e.conferido;save(`day:${day}`,d);render()});r.querySelector("[data-remove]").onclick=()=>{d.entries=d.entries.filter(x=>x.id!==id);save(`day:${day}`,d);render()}});$("#add").onclick=()=>{d.entries.push({id:crypto.randomUUID(),comanda:"",taxa:"",ok:false});save(`day:${day}`,d);render()};document.querySelectorAll("[data-shift]").forEach(b=>b.onclick=()=>shiftDate("day",+b.dataset.shift))}
function shiftDate(kind,n){let k=kind==="day"?day:expDay,[y,m,d]=k.split("-").map(Number),x=new Date(y,m-1,d+n);k=`${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`;if(kind==="day")day=k;else expDay=k;render()}
function renderExpenses(){const d=getExp(expDay),rows=(d.items||[]).map(e=>`<div class="entry expense" data-id="${esc(e.id)}"><select data-f="cat"><option value="combustivel" ${e.cat==="combustivel"?"selected":""}>⛽ Combustível</option><option value="oleo" ${e.cat==="oleo"?"selected":""}>🛢️ Troca de óleo</option><option value="manutencao" ${e.cat==="manutencao"?"selected":""}>🔧 Manutenção</option><option value="pneu" ${e.cat==="pneu"?"selected":""}>🛞 Pneu</option><option value="alimentacao" ${e.cat==="alimentacao"?"selected":""}>🍔 Alimentação</option><option value="outros" ${e.cat==="outros"?"selected":""}>📦 Outros</option></select><input data-f="desc" placeholder="Detalhe / anotação" value="${esc(e.desc||"")}"><input data-f="val" type="number" inputmode="decimal" placeholder="Valor" value="${esc(e.val||"")}"><button class="trash" data-remove>×</button></div>`).join(""),total=d.items.reduce((s,e)=>s+(+e.val||0),0);return`<div class="daynav"><button class="navbtn" data-exp-shift="-1">‹</button><div class="daycenter"><strong>${dateLabel(expDay)}</strong><input id="expdate" type="date" value="${expDay}"></div><button class="navbtn" data-exp-shift="1">›</button></div><div class="card"><div class="title">Gastos e anotações</div>${rows||'<div class="empty">Nenhum gasto lançado.</div>'}<button class="add" id="addexp">+ Novo gasto</button><div class="sum total"><span>Total do dia</span><b>${brl(total)}</b></div></div>`}
function bindExpenses(){const d=getExp(expDay);$("#expdate").onchange=e=>{expDay=e.target.value;render()};$("#addexp").onclick=()=>{d.items.push({id:crypto.randomUUID(),cat:"combustivel",desc:"",val:""});save(`exp:${expDay}`,d);render()};document.querySelectorAll(".expense").forEach(r=>{const id=r.dataset.id,e=d.items.find(x=>x.id===id);r.querySelectorAll("input,select").forEach(i=>i.onchange=()=>{e[i.dataset.f]=i.value;save(`exp:${expDay}`,d);render()});r.querySelector("[data-remove]").onclick=()=>{d.items=d.items.filter(x=>x.id!==id);save(`exp:${expDay}`,d);render()}});document.querySelectorAll("[data-exp-shift]").forEach(b=>b.onclick=()=>shiftDate("exp",+b.dataset.expShift))}
function renderMechanic(){const m=getMech(),d=getDay(day),km=+d.kmFinal||+m.motoKm||0,last=+m.ultimaTroca||0,int=+m.intervalo||0,next=last+int,rest=next-km,status=!next?"":rest<=0?"over":rest<=300?"att":"ok",label=status==="over"?"TROCA VENCIDA":status==="att"?"ATENÇÃO":"EM DIA";return`<div class="card mechhero"><div class="mechicon">🔧</div><div><div class="title" style="margin:0">Mecânica</div><div class="muted">Controle personalizado da sua moto</div></div></div><div class="card"><div class="title">🛢️ Troca de óleo</div><div class="kv"><span>KM da última troca</span><input id="last" style="width:130px" type="number" value="${esc(m.ultimaTroca)}"></div><div class="kv"><span>Intervalo definido por você</span><input id="int" style="width:130px" type="number" value="${esc(m.intervalo)}" placeholder="Ex.: 3000"></div><div class="kv"><span>Próxima troca</span><b class="bigblue">${next?next.toLocaleString("pt-BR")+" km":"—"}</b></div><div class="kv"><span>KM atual</span><b>${km?km.toLocaleString("pt-BR")+" km":"—"}</b></div><div class="kv"><span>Faltam</span><b>${next?(rest>0?rest.toLocaleString("pt-BR")+" km":"0 km"):"—"}</b></div>${next?`<div style="margin-top:10px"><span class="status ${status}">${label}</span></div>`:""}<button class="primary" id="savemech">SALVAR CONFIGURAÇÃO</button></div><div class="notice">A KM final registrada no fechamento do dia é usada automaticamente como KM atual da mecânica.</div>`}
function bindMechanic(){$("#last").onchange=()=>{const m=getMech();m.ultimaTroca=$("#last").value;save("mechanica",m);render()};$("#int").onchange=()=>{const m=getMech();m.intervalo=$("#int").value;save("mechanica",m);render()};$("#savemech").onclick=()=>alert("Configuração salva automaticamente.")}
function monthKeys(){const p=`${month.getFullYear()}-${pad(month.getMonth()+1)}-`,ks=[],pre=userKey("day:");for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||"";if(k.startsWith(pre)&&k.slice(pre.length).startsWith(p))ks.push(k.slice(pre.length))}return[...new Set(ks)].sort()}
function renderMonth(){const ks=monthKeys(),ds=ks.map(getDay),km=ds.reduce((s,d)=>s+totals(d).km,0),ent=ds.reduce((s,d)=>s+d.entries.length,0),tax=ds.reduce((s,d)=>s+totals(d).taxas,0),arr=ds.reduce((s,d)=>s+(+d.arrancada||0),0),exp=ks.reduce((s,k)=>s+getExp(k).items.reduce((x,e)=>x+(+e.val||0),0),0),initial=ds.length?Math.min(...ds.map(d=>+d.kmInicial||Infinity)):0,final=ds.length?Math.max(...ds.map(d=>+d.kmFinal||0)):0;return`<div class="card"><div class="monthnav"><button class="navbtn" data-month="-1">‹</button><strong>${month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</strong><button class="navbtn" data-month="1">›</button></div></div><div class="grid"><div class="stat"><div class="l">Entregas</div><div class="v blue">${ent}</div></div><div class="stat"><div class="l">KM rodados</div><div class="v blue">${km.toLocaleString("pt-BR")} km</div></div><div class="stat"><div class="l">Recebido</div><div class="v green">${brl(tax+arr)}</div></div><div class="stat"><div class="l">Gastos</div><div class="v red">${brl(exp)}</div></div></div><div class="card"><div class="sum"><span>KM inicial do mês</span><b>${initial?initial.toLocaleString("pt-BR"):"—"}</b></div><div class="sum"><span>KM final do mês</span><b>${final?final.toLocaleString("pt-BR"):"—"}</b></div><div class="sum total"><span>Total rodado</span><b class="blue">${km.toLocaleString("pt-BR")} km</b></div><div class="sum"><span>Média por dia lançado</span><b>${ds.length?Math.round(km/ds.length):0} km/dia</b></div></div><div class="card"><div class="title">Dias lançados</div>${ks.map(k=>{const t=totals(getDay(k));return`<div class="dayitem"><span>${dateLabel(k)}</span><span>${t.ent} entregas</span><b class="right blue">${t.km} km</b></div>`}).join("")||'<div class="empty">Nenhum dia lançado neste mês.</div>'}</div>`}
function bindMonth(){document.querySelectorAll("[data-month]").forEach(b=>b.onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+ +b.dataset.month,1);render()})}
function backup(){const data={version:3,user,exportedAt:new Date().toISOString(),days:{},expenses:{},mechanica:getMech()},pre=userKey("");for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||"";if(k.startsWith(pre+"day:"))data.days[k.slice((pre+"day:").length)]=safeJSON(k,null);if(k.startsWith(pre+"exp:"))data.expenses[k.slice((pre+"exp:").length)]=safeJSON(k,null)}const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`delivery-backup-${today()}.json`;a.click()}
function showLogin(error=""){document.body.innerHTML=`<div class="login"><div class="loginbox"><div class="biglogo"></div><h1>Delivery Comandas</h1><p>${loginMode==="login"?"Controle suas entregas de forma simples":"Criar novo usuário"}</p><div class="card"><label>Usuário</label><input id="u" autocomplete="username"><label>Senha</label><input id="p" type="password" autocomplete="${loginMode==="login"?"current-password":"new-password"}">${error?`<div class="notice warn">${esc(error)}</div>`:""}<button class="primary" id="go">${loginMode==="login"?"ENTRAR":"CRIAR CONTA"}</button><button class="add" id="switch">${loginMode==="login"?"Criar novo usuário":"Já tenho uma conta"}</button></div><div class="small">Seus lançamentos ficam separados por usuário neste aparelho.</div></div></div>`;$("#go").onclick=()=>{const u=$("#u").value.trim().toLowerCase(),p=$("#p").value;if(loginMode==="register"){const e=register(u,p);if(e)return showLogin(e);render()}else{const e=doLogin(u,p);if(e)return showLogin(e);render()}};$("#switch").onclick=()=>{loginMode=loginMode==="login"?"register":"login";showLogin()}}
function render(){if(!user){showLogin();return}const c=view==="day"?renderDay():view==="expenses"?renderExpenses():view==="mechanic"?renderMechanic():renderMonth();shell(c);$("#backup").onclick=backup;$("#logout").onclick=logout;document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});if(view==="day")bindDay();if(view==="expenses")bindExpenses();if(view==="mechanic")bindMechanic();if(view==="month")bindMonth()}
render();
