import "./tools.js?v=15";
import "./entrega365-features.js?v=80";
import "./session-policy.js?v=80";
import "./entrega365-theme-v2.js?v=80";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-auth.js";
const firebaseConfig={apiKey:"AIzaSyDaOy4D6Jr3LPTKEdkHC3OQjiv8_ZySPYU",authDomain:"entrega365.firebaseapp.com",projectId:"entrega365",storageBucket:"entrega365.firebasestorage.app",messagingSenderId:"686578751112",appId:"1:686578751112:web:4c0f8e4b3a569e7297313d",measurementId:"G-RPRXBXXDJK"};
const auth=getAuth(initializeApp(firebaseConfig)),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});
const SESSION="dcv2:session",FULL_LOGO="./logo-entrega365.jpg?v=81",ICON_LOGO="./app-icon.svg?v=81";
function improveLoginVisual(){if(document.getElementById("entrega365-login-v14"))return;const s=document.createElement("style");s.id="entrega365-login-v14";s.textContent=`.login{align-items:flex-start!important;padding:28px 14px 40px!important;overflow-y:auto}.loginbox{max-width:430px!important}.biglogo{width:min(94vw,520px)!important;height:300px!important;margin:0 auto 2px!important;border-radius:0!important;background:none!important;border:0!important;box-shadow:none!important}.biglogo img{display:block;width:100%;height:100%;object-fit:contain}.loginbox .card{padding:20px!important;border-radius:22px!important}.loginbox input{min-height:52px;font-size:16px}.loginbox .primary{min-height:54px;font-size:16px;margin-top:15px!important}`;document.head.appendChild(s)}
function fixLogo(){document.querySelectorAll(".biglogo").forEach(el=>{el.style.background="none";el.style.border="0";el.style.borderRadius="0";el.innerHTML="";const img=document.createElement("img");img.src=FULL_LOGO;img.alt="Entrega365";img.style.cssText="display:block;width:100%;height:100%;object-fit:contain";el.appendChild(img)});document.querySelectorAll(".logo").forEach(el=>{el.style.background="none";el.style.backgroundImage=`url("${ICON_LOGO}")`;el.style.backgroundSize="contain";el.style.backgroundPosition="center";el.style.backgroundRepeat="no-repeat";el.style.border="0";el.style.boxShadow="none"});const icon=document.querySelector('link[rel="icon"]');if(icon)icon.href=ICON_LOGO}
function addGoogleButton(){const card=document.querySelector(".loginbox .card");if(!card||document.getElementById("google-login"))return;const b=document.createElement("button");b.id="google-login";b.type="button";b.textContent="CONTINUAR COM GOOGLE";b.style.cssText="width:100%;border:1px solid #666;border-radius:12px;background:#fff;color:#222;font-weight:900;padding:13px;margin-top:10px";b.onclick=async()=>{try{const r=await signInWithPopup(auth,provider),u=r.user;localStorage.setItem(SESSION,"google:"+u.uid);localStorage.setItem("entrega365:firebaseUid",u.uid);localStorage.setItem("entrega365:email",u.email||"");localStorage.setItem("entrega365:displayName",u.displayName||"");localStorage.setItem("entrega365:lastGoogleAccount",u.email||"");location.reload()}catch(e){alert(`Não foi possível entrar com Google (${e?.code||"erro"}).`)}};card.appendChild(b)}
function addSavedGoogle(){const card=document.querySelector(".loginbox .card"),email=localStorage.getItem("entrega365:lastGoogleAccount");if(!card||!email||document.getElementById("saved-google"))return;const d=document.createElement("div");d.id="saved-google";d.style.cssText="margin:0 0 10px;padding:10px 12px;border:1px solid #444;border-radius:12px;color:#aaa;font-size:12px;text-align:left";d.innerHTML=`Conta Google salva: <b style="color:#fff">${email.replace(/</g,'&lt;')}</b>`;card.prepend(d)}
function addBackupButton(){const card=document.querySelector(".loginbox .card");if(!card||document.getElementById("backup-login"))return;const input=document.createElement("input");input.type="file";input.accept=".json";input.style.display="none";const b=document.createElement("button");b.id="backup-login";b.type="button";b.textContent="ENTRAR / RESTAURAR BACKUP";b.className="add";b.style.cssText="width:100%;margin-top:10px";b.onclick=()=>input.click();card.append(input,b);input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d.user)throw 0;const p="dcv2:"+d.user+":";Object.entries(d.days||{}).forEach(([k,v])=>localStorage.setItem(p+"day:"+k,JSON.stringify(v)));Object.entries(d.expenses||{}).forEach(([k,v])=>localStorage.setItem(p+"exp:"+k,JSON.stringify(v)));if(d.mechanica)localStorage.setItem(p+"mechanica",JSON.stringify(d.mechanica));localStorage.setItem(SESSION,d.user);location.reload()}catch{alert("Backup inválido ou corrompido.")}}}
function setupLogin(){improveLoginVisual();fixLogo();if(localStorage.getItem(SESSION))return;if(typeof window.showLogin==="function")window.showLogin();improveLoginVisual();fixLogo();addGoogleButton();addSavedGoogle();addBackupButton();setTimeout(fixLogo,200)}
window.backup=window.backup||function(){};onAuthStateChanged(auth,u=>{if(u&&!localStorage.getItem(SESSION)){localStorage.setItem(SESSION,"google:"+u.uid);localStorage.setItem("entrega365:firebaseUid",u.uid);localStorage.setItem("entrega365:email",u.email||"");localStorage.setItem("entrega365:displayName",u.displayName||"");localStorage.setItem("entrega365:lastGoogleAccount",u.email||"");location.reload()}});const oldLogout=window.logout;window.logout=async()=>{try{await signOut(auth)}catch{}if(oldLogout)oldLogout();else{localStorage.removeItem(SESSION);location.reload()}};
import("./drive-backup.js?v=81").then(m=>m.initDriveBackup(auth)).catch(e=>console.warn("Drive backup indisponível",e));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(setupLogin,80));else setTimeout(setupLogin,80);