import "./tools.js?v=18";
import "./entrega365-features.js?v=85";
import "./session-policy.js?v=89";
import "./entrega365-theme-v2.js?v=85";
import "./entrega365-pro.js?v=8";
import "./mobile-layout-fix.css?v=1";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithRedirect, getRedirectResult, setPersistence, browserLocalPersistence, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-auth.js";
const firebaseConfig={apiKey:"AIzaSyDaOy4D6Jr3LPTKEdkHC3OQjiv8_ZySPYU",authDomain:"www.entrega365.com.br",projectId:"entrega365",storageBucket:"entrega365.firebasestorage.app",messagingSenderId:"686578751112",appId:"1:686578751112:web:4c0f8e4b3a569e7297313d",measurementId:"G-RPRXBXXDJK"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),SESSION="dcv2:session";
let redirectProcessing=true;
function improve(){if(document.getElementById("e365-google-style"))return;const s=document.createElement("style");s.id="e365-google-style";s.textContent=`.login{align-items:flex-start!important;padding:24px 14px 40px!important;overflow-y:auto}.loginbox{max-width:430px!important}.biglogo{width:min(94vw,520px)!important;height:300px!important;margin:0 auto 2px!important;background:none!important;border:0!important;box-shadow:none!important}.biglogo img{display:block;width:100%;height:100%;object-fit:contain}.loginbox .card{padding:20px!important;border-radius:22px!important}.google-only{display:flex;flex-direction:column;gap:10px}.google-account,.google-new{width:100%;border:1px solid #555;border-radius:14px;background:#262626;color:#fff;padding:14px;font-weight:900}.google-account{display:flex;align-items:center;gap:12px;text-align:left}.google-account:hover,.google-new:hover{border-color:#ffd000}.google-icon{width:30px;height:30px;border-radius:50%;background:#fff;display:flex;align-items:center;justify-content:center;color:#4285f4;font-size:18px;flex:none}.google-main{flex:1;min-width:0}.google-main b,.google-main small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.google-main small{color:#aaa;font-weight:500;margin-top:2px}.google-new{color:#ffd000;background:#1e1e1e}`;document.head.appendChild(s)}
function fixLogo(){document.querySelectorAll(".biglogo").forEach(el=>{el.innerHTML="";const img=document.createElement("img");img.src="./logo-entrega365.jpg?v=96";img.alt="Entrega365";img.style.cssText="display:block;width:100%;height:100%;object-fit:contain";el.appendChild(img)})}
function saveUser(u){localStorage.setItem("entrega365:firebaseUid",u.uid);localStorage.setItem("entrega365:email",u.email||"");localStorage.setItem("entrega365:displayName",u.displayName||"");localStorage.setItem("entrega365:lastGoogleAccount",u.email||"");localStorage.setItem(SESSION,"google:"+u.uid)}
function error(e){const c=e?.code||"unknown";const m={"auth/unauthorized-domain":"O domínio ainda não está autorizado no Firebase.","auth/operation-not-allowed":"O login com Google não está habilitado.","auth/network-request-failed":"Falha de conexão.","auth/web-storage-unsupported":"O navegador não permite o armazenamento necessário.","auth/internal-error":"O Google/Firebase não conseguiu concluir a sessão."};alert("Não foi possível entrar com Google.\n\n"+(m[c]||"Erro: "+c))}
async function finish(){try{await setPersistence(auth,browserLocalPersistence);const r=await getRedirectResult(auth);if(r?.user){saveUser(r.user);location.replace(location.href.split("?")[0].split("#")[0]);return true}}catch(e){error(e)}finally{redirectProcessing=false}return false}
async function google(chooser=true){try{const p=new GoogleAuthProvider();if(chooser)p.setCustomParameters({prompt:"select_account"});await setPersistence(auth,browserLocalPersistence);await signInWithRedirect(auth,p)}catch(e){error(e)}}
function loginScreen(){const root=document.getElementById("app");if(!root)return;const email=localStorage.getItem("entrega365:lastGoogleAccount")||localStorage.getItem("entrega365:email")||"";root.innerHTML=`<div class="login"><div class="loginbox"><div class="biglogo"></div><h1>Entrega365</h1><p>Entre com sua conta Google para continuar</p><div class="card"><div class="google-only">${email?`<button class="google-account" data-google-account><span class="google-icon">G</span><span class="google-main"><b>${email.replace(/</g,"&lt;")}</b><small>Toque para entrar com esta conta</small></span><span>›</span></button>`:`<button class="google-new" data-google-new>ENTRAR COM GOOGLE</button>`}<button class="google-new" data-google-new>${email?"USAR OUTRA CONTA GOOGLE":"ENTRAR COM GOOGLE"}</button></div></div></div></div>`;root.querySelector("[data-google-account]")?.addEventListener("click",()=>google(false));root.querySelectorAll("[data-google-new]").forEach(b=>b.addEventListener("click",()=>google(true)));fixLogo()}
function setup(){improve();if(redirectProcessing)return;const s=localStorage.getItem(SESSION);if(s&&!s.startsWith("google:")){localStorage.removeItem(SESSION);localStorage.removeItem("entrega365:email");localStorage.removeItem("entrega365:lastGoogleAccount")}if(!auth.currentUser)loginScreen();improve();fixLogo()}
onAuthStateChanged(auth,u=>{if(u){saveUser(u);if(document.querySelector(".google-only"))location.reload()}});
const oldLogout=window.logout;window.logout=async()=>{try{await signOut(auth)}catch{}if(oldLogout)oldLogout();else{localStorage.removeItem(SESSION);location.reload()}};
import("./drive-backup.js?v=96").then(m=>m.initDriveBackup(auth)).catch(()=>{});
(async()=>{await finish();setup()})();
