const FULL_LOGO="./logo-entrega365.jpg?v=122";
const ICON_LOGO="./app-icon.svg?v=122";
function applyEntrega365Brand(){document.querySelectorAll(".biglogo").forEach(el=>{el.style.background="none";el.style.border="0";el.style.borderRadius="0";el.style.boxShadow="none";el.innerHTML="";const img=document.createElement("img");img.src=FULL_LOGO;img.alt="Entrega365";img.decoding="async";img.loading="eager";img.style.cssText="display:block;width:100%;height:100%;object-fit:contain";el.appendChild(img);el.style.width="min(94vw,520px)";el.style.height="300px"});document.querySelectorAll(".logo").forEach(el=>{el.style.background="none";el.style.backgroundImage=`url(\"${ICON_LOGO}\")`;el.style.backgroundSize="contain";el.style.backgroundPosition="center";el.style.backgroundRepeat="no-repeat";el.style.border="0";el.style.boxShadow="none"});const icon=document.querySelector('link[rel="icon"]');if(icon)icon.href=ICON_LOGO}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",applyEntrega365Brand);else applyEntrega365Brand();setTimeout(applyEntrega365Brand,250);
(function loadScript(src,key,type){if(window[key])return;window[key]=true;const s=document.createElement('script');s.src=src;s.async=false;if(type)s.type=type;s.onerror=()=>console.warn(src+' indisponível');document.head.appendChild(s)})('./plus-buttons-fix.js?v=3','__e365PlusButtonsFixLoader');
(function loadLayoutReorg(){if(window.__e365LayoutReorgLoader)return;window.__e365LayoutReorgLoader=true;const s=document.createElement('script');s.src='./layout-reorg.js?v=7';s.async=false;s.onerror=()=>console.warn('Reorganização do layout indisponível');document.head.appendChild(s)})();
(function loadGeolocation(){if(window.__e365GeolocationLoader)return;window.__e365GeolocationLoader=true;const s=document.createElement('script');s.src='./native-geolocation.js?v=1';s.async=false;s.onerror=()=>console.warn('Geolocalização indisponível');document.head.appendChild(s)})();
(function loadPostgresSync(){if(window.__e365PostgresSyncLoader)return;window.__e365PostgresSyncLoader=true;const s=document.createElement("script");s.src="./data-sync.js?v=1";s.async=false;s.onerror=()=>console.warn("Sincronização PostgreSQL indisponível");document.head.appendChild(s)})();
(function loadManualBackup(){if(window.__e365ManualBackupLoader)return;window.__e365ManualBackupLoader=true;const s=document.createElement('script');s.src='./manual-backup-ui.js?v=4';s.async=false;s.onerror=()=>console.warn('Backup local indisponível');document.head.appendChild(s)})();
(function fixMonthlyDeliveryTotal(){if(window.__e365MonthlyDeliveryTotalFix)return;window.__e365MonthlyDeliveryTotalFix=true;function update(){try{if(typeof view!=="undefined"&&view!=="month")return;if(typeof user==="undefined"||!user||typeof monthKeys!=="function"||typeof getDay!=="function"||typeof totals!=="function")return;const total=monthKeys().reduce((sum,k)=>sum+totals(getDay(k)).ent,0);const stats=[...document.querySelectorAll("main .stat")];const stat=stats.find(x=>/entregas/i.test(x.querySelector(".l")?.textContent||""));if(stat){const value=stat.querySelector(".v");if(value)value.textContent=String(total)}}catch(e){console.warn("Total mensal de entregas:",e)}}window.addEventListener("e365-data-changed",()=>setTimeout(update,0));new MutationObserver(()=>setTimeout(update,0)).observe(document.documentElement,{childList:true,subtree:true});setTimeout(update,300)})();