/* Entrega365 — Comunidade + Marketplace — PostgreSQL backend */
const API='/api';
const MARKET_DEFAULT='https://meli.la/1Komyrh';
const ADMIN='entrega365.suporte@gmail.com';
let modal=null, view='community', posts=[];
function user(){const authUser=window.entrega365Auth?.auth?.currentUser||window.__e365Auth?.currentUser;return authUser||window.e365GetCurrentUser?.()||null}
async function authUser(){let u=user();if(u?.getIdToken)return u;for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,250));u=user();if(u?.getIdToken)return u}throw new Error('Sessão não autenticada. Aguarde o login terminar e tente novamente.')}
async function token(){const u=await authUser();return u.getIdToken()}
async function api(path,opts={}){const t=await token();const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+t,...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Erro HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function date(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Agora'}
function media(p){const u=p.url||'';if(!u)return '';if(/^data:image\/(?:jpeg|png|webp|gif);base64,/i.test(u)){return `<div class="cm-image"><img src="${u}" alt="Imagem da publicação" loading="lazy"></div>`}const m=u.match(/[?&]v=([^&#]+)/)||u.match(/youtu\.be\/([^?&#/]+)/)||u.match(/youtube\.com\/(?:shorts|embed)\/([^?&#/]+)/);if(m)return `<div class="cm-media"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(m[1])}" loading="lazy" allowfullscreen></iframe></div>`;return `<a class="cm-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">🔗 Abrir conteúdo</a>`}
function styles(){if(document.getElementById('e365-cm-style'))return;const s=document.createElement('style');s.id='e365-cm-style';s.textContent=`.cm-overlay{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.72);display:flex;align-items:flex-end;justify-content:center}.cm-sheet{width:min(760px,100%);max-height:94dvh;overflow:auto;background:#171717;border:1px solid #383838;border-radius:24px 24px 0 0;padding:14px}.cm-head{display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#171717;z-index:2;padding-bottom:10px;border-bottom:1px solid #333}.cm-title{font-size:20px;font-weight:900}.cm-close{width:40px;height:40px;border:1px solid #444;border-radius:12px;background:#222;color:#fff;font-size:20px}.cm-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.cm-tab,.cm-btn{padding:11px;border:1px solid #444;border-radius:11px;background:#222;color:#ddd;font-weight:800}.cm-tab.active{color:#ffd000;border-color:#ffd000}.cm-card{background:linear-gradient(160deg,#202020,#292929);border:1px solid #383838;border-radius:16px;padding:14px;margin:10px 0}.cm-form{display:grid;gap:9px}.cm-form textarea,.cm-form input,.cm-form select{width:100%;background:#151515;color:#fff;border:1px solid #444;border-radius:11px;padding:11px;box-sizing:border-box}.cm-primary{width:100%;padding:12px;border:0;border-radius:11px;background:#ffd000;color:#111;font-weight:900}.cm-post{padding:14px}.cm-author{font-size:13px;font-weight:900}.cm-muted{color:#999;font-size:12px}.cm-text{white-space:pre-wrap;line-height:1.5;margin:9px 0}.cm-actions{display:flex;gap:8px}.cm-actions button{flex:1}.cm-media,.cm-image{background:#090909;border-radius:12px;overflow:hidden;margin:10px 0}.cm-media{aspect-ratio:16/9}.cm-media iframe{width:100%;height:100%;border:0}.cm-image img{display:block;width:100%;height:auto;max-height:520px;object-fit:contain}.cm-link{display:block;padding:11px;border:1px solid #444;border-radius:10px;color:#ffd000;text-align:center;text-decoration:none}.cm-comments{border-top:1px solid #333;margin-top:10px;padding-top:8px}.cm-comment{padding:7px 0;border-bottom:1px solid #292929}.cm-comment-form{display:flex;gap:7px;margin-top:8px}.cm-comment-form input{flex:1}.cm-comment-form button{width:45px}.cm-empty,.cm-error{text-align:center;padding:25px;color:#999}.cm-error{color:#ff6b60}.cm-store{text-align:center;padding:24px 10px}.cm-store-btn{display:block;padding:13px;background:#ffd000;color:#111;border-radius:11px;text-decoration:none;font-weight:900;margin-top:12px}.cm-image-file{font-size:13px}`;document.head.appendChild(s)}
function shell(){styles();if(modal)return modal;modal=document.createElement('div');modal.className='cm-overlay';modal.innerHTML=`<div class="cm-sheet"><div class="cm-head"><div class="cm-title">＋ Entrega365</div><button class="cm-close">×</button></div><div class="cm-tabs"><button class="cm-tab" data-v="community">👥 Comunidade</button><button class="cm-tab" data-v="marketplace">🛍️ Marketplace</button></div><div id="cm-content"></div></div>`;document.body.appendChild(modal);modal.querySelector('.cm-close').onclick=()=>modal.style.display='none';modal.querySelectorAll('.cm-tab').forEach(b=>b.onclick=()=>render(b.dataset.v));return modal}
async function render(v='community'){view=v;shell();modal.style.display='flex';modal.querySelectorAll('.cm-tab').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='marketplace')return renderMarket();return renderCommunity()}
async function renderCommunity(){const c=modal.querySelector('#cm-content');c.innerHTML=`<div class="cm-card"><b>📣 Comunidade Entrega365</b><div class="cm-muted">Publicações sincronizadas pelo backend PostgreSQL.</div></div><div class="cm-card cm-form"><textarea id="cm-text" maxlength="4000" placeholder="O que você quer compartilhar?"></textarea><select id="cm-type"><option value="text">Somente texto</option><option value="youtube">YouTube</option><option value="instagram">Instagram</option><option value="image">Imagem</option></select><input id="cm-url" type="url" placeholder="Link opcional"><label class="cm-image-file">📷 Adicionar imagem <input id="cm-image" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><button id="cm-publish" class="cm-primary">PUBLICAR NA COMUNIDADE</button></div><div id="cm-feed"><div class="cm-empty">Carregando publicações…</div></div>`;modal.querySelector('#cm-publish').onclick=publish;modal.querySelector('#cm-image').onchange=()=>{if(modal.querySelector('#cm-image').files[0])modal.querySelector('#cm-type').value='image'};await loadPosts()}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!/^image\/(jpeg|png|webp|gif)$/i.test(file.type))return reject(new Error('Escolha uma imagem JPG, PNG, WEBP ou GIF.'));const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=1280;let w=img.naturalWidth,h=img.naturalHeight;if(w>max||h>max){const scale=Math.min(max/w,max/h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.72))};img.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));img.src=reader.result};reader.onerror=()=>reject(new Error('Não foi possível carregar a imagem.'));reader.readAsDataURL(file)})}
async function loadPosts(){try{const d=await api('/community/posts?limit=50');posts=d.posts||[];renderFeed()}catch(e){modal.querySelector('#cm-feed').innerHTML=`<div class="cm-error">Não foi possível carregar as publicações.<br>${esc(e.message)}</div>`}}
function renderFeed(){const el=modal.querySelector('#cm-feed');if(!posts.length){el.innerHTML='<div class="cm-empty">Ainda não há publicações. Seja o primeiro! 🚀</div>';return}el.innerHTML=posts.map(p=>`<div class="cm-card cm-post"><div class="cm-author">${esc(p.author_name||'Entregador')} <span class="cm-muted">• ${date(p.created_at)}</span></div><div class="cm-text">${esc(p.text||'')}</div>${media(p)}<div class="cm-actions"><button class="cm-btn" data-like="${p.id}">${p.liked?'❤️':'🤍'} ${p.like_count||0}</button><button class="cm-btn" data-comments="${p.id}">💬 ${p.comment_count||0}</button></div><div class="cm-comments" id="comments-${p.id}"></div></div>`).join('');el.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>like(Number(b.dataset.like)));el.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>comments(Number(b.dataset.comments)))}
async function publish(){const b=modal.querySelector('#cm-publish'),text=modal.querySelector('#cm-text').value.trim(),type=modal.querySelector('#cm-type').value,url=modal.querySelector('#cm-url').value.trim(),file=modal.querySelector('#cm-image').files[0];if(!text&&!url&&!file)return alert('Digite um texto, informe um link ou adicione uma imagem.');b.disabled=true;b.textContent='PREPARANDO…';try{const image=await compressImage(file);const finalUrl=image||url;const finalType=image?'image':type;await api('/community/posts',{method:'POST',body:JSON.stringify({text,type:finalType,url:finalUrl})});modal.querySelector('#cm-text').value='';modal.querySelector('#cm-url').value='';modal.querySelector('#cm-image').value='';await loadPosts()}catch(e){alert('Não foi possível publicar: '+e.message)}finally{b.disabled=false;b.textContent='PUBLICAR NA COMUNIDADE'}}
async function like(id){const p=posts.find(x=>x.id===id);try{const d=await api('/community/likes',{method:p?.liked?'DELETE':'POST',body:JSON.stringify({postId:id})});if(p){p.liked=d.liked;p.like_count=d.likeCount}renderFeed()}catch(e){alert(e.message)}}
async function comments(id){const box=modal.querySelector('#comments-'+id);if(box.dataset.loaded==='1'){box.dataset.open=box.dataset.open==='1'?'0':'1';box.style.display=box.dataset.open==='1'?'block':'none';return}try{const d=await api('/community/comments?postId='+id);box.innerHTML=(d.comments||[]).map(x=>`<div class="cm-comment"><b>${esc(x.author_name)}</b><div>${esc(x.text)}</div></div>`).join('')+`<div class="cm-comment-form"><input id="comment-input-${id}" placeholder="Escreva um comentário"><button class="cm-primary" id="comment-btn-${id}">➤</button></div>`;box.dataset.loaded='1';box.dataset.open='1';box.querySelector('button').onclick=()=>addComment(id);box.style.display='block'}catch(e){box.innerHTML='<div class="cm-error">'+esc(e.message)+'</div>'}}
async function addComment(id){const input=modal.querySelector('#comment-input-'+id);if(!input?.value.trim())return;try{await api('/community/comments',{method:'POST',body:JSON.stringify({postId:id,text:input.value.trim()})});boxReload(id)}catch(e){alert(e.message)}}
async function boxReload(id){const box=modal.querySelector('#comments-'+id);if(!box)return;box.dataset.loaded='0';await comments(id)}
async function renderMarket(){const c=modal.querySelector('#cm-content');c.innerHTML='<div class="cm-store">🛍️<h2>Marketplace Entrega365</h2><p class="cm-muted">Loja configurada pelo backend PostgreSQL.</p><div id="cm-store-action">Carregando…</div></div>'+(String(user()?.email||'').toLowerCase()===ADMIN?'<div class="cm-card cm-form"><input id="cm-store-url" placeholder="Link do Mercado Livre"><button id="cm-save" class="cm-primary">SALVAR LOJA</button></div>':'');try{const d=await api('/marketplace');const url=d.affiliateUrl||MARKET_DEFAULT;c.querySelector('#cm-store-action').innerHTML=`<a class="cm-store-btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">🛒 VISITAR LOJA</a>`;if(c.querySelector('#cm-store-url')){c.querySelector('#cm-store-url').value=url;c.querySelector('#cm-save').onclick=async()=>{try{await api('/marketplace',{method:'PUT',body:JSON.stringify({affiliateUrl:c.querySelector('#cm-store-url').value})});alert('Loja salva no PostgreSQL.');await renderMarket()}catch(e){alert(e.message)}}}}catch(e){c.querySelector('#cm-store-action').innerHTML='<div class="cm-error">'+esc(e.message)+'</div>'}}
function ensureButton(){styles();if(document.getElementById('e365-community-plus'))return;const actions=document.querySelector('header .actions'),tabs=document.querySelector('.tabs');const b=document.createElement('button');b.id='e365-community-plus';b.type='button';b.title='Comunidade e Marketplace';b.innerHTML='+';b.className=actions?'ico':'tab';b.onclick=()=>render('community');(actions||tabs)?.appendChild(b)}
const boot=()=>setTimeout(ensureButton,300);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.e365CommunityOpen=()=>render('community');window.e365MarketplaceOpen=()=>render('marketplace');