/* Entrega365 — Comunidade + Marketplace — PostgreSQL backend */
const API='/api';
const MARKET_DEFAULT='https://meli.la/1Komyrh';
const ADMIN='entrega365.suporte@gmail.com';
let modal=null,view='community',posts=[];
function user(){const authUser=window.entrega365Auth?.auth?.currentUser||window.__e365Auth?.currentUser;return authUser||window.e365GetCurrentUser?.()||null}
async function authUser(){let u=user();if(u?.getIdToken)return u;for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,250));u=user();if(u?.getIdToken)return u}throw new Error('Sessão não autenticada. Aguarde o login terminar e tente novamente.')}
async function token(){const u=await authUser();return u.getIdToken()}
async function api(path,opts={}){const t=await token();const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+t,...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Erro HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function date(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Agora'}
function media(p){const u=p.url||'';if(!u)return '';if(/^data:image\/(?:jpeg|png|webp|gif);base64,/i.test(u))return `<div class="cm-image"><img src="${u}" alt="Imagem da publicação" loading="lazy"></div>`;const m=u.match(/[?&]v=([^&#]+)/)||u.match(/youtu\.be\/([^?&#/]+)/)||u.match(/youtube\.com\/(?:shorts|embed)\/([^?&#/]+)/);if(m)return `<div class="cm-media"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(m[1])}" loading="lazy" allowfullscreen></iframe></div>`;return `<a class="cm-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">🔗 Abrir conteúdo</a>`}
function styles(){if(document.getElementById('e365-cm-style'))return;const s=document.createElement('style');s.id='e365-cm-style';s.textContent=`
.cm-overlay{position:fixed;inset:0;z-index:1000;background:#101010;color:#f5f5f5;display:block;overflow:hidden}
.cm-sheet{width:100%;height:100dvh;overflow:auto;background:radial-gradient(circle at 50% -15%,#292929 0,transparent 42%),#101010}
.cm-head{position:sticky;top:0;z-index:20;display:flex;align-items:center;justify-content:space-between;height:64px;padding:8px max(16px,calc((100% - 1180px)/2));background:rgba(16,16,16,.94);backdrop-filter:blur(18px);border-bottom:1px solid #333}
.cm-title{font-size:20px;font-weight:950;letter-spacing:.2px}.cm-title small{display:block;font-size:10px;color:#ffd000;font-weight:700;letter-spacing:.7px;margin-top:-2px}
.cm-close{width:40px;height:40px;border:1px solid #444;border-radius:12px;background:#222;color:#fff;font-size:20px}.cm-close:hover{border-color:#ffd000;color:#ffd000}
.cm-tabs{position:sticky;top:64px;z-index:19;display:flex;gap:8px;padding:10px max(16px,calc((100% - 1180px)/2));background:rgba(16,16,16,.92);border-bottom:1px solid #292929;backdrop-filter:blur(14px)}
.cm-tab{padding:10px 18px;border:1px solid #444;border-radius:999px;background:#202020;color:#bbb;font-weight:850}.cm-tab.active{color:#111;background:#ffd000;border-color:#ffd000}
.cm-layout{width:min(1180px,100%);margin:auto;padding:18px 16px 60px;display:grid;grid-template-columns:250px minmax(0,680px) 220px;gap:18px;align-items:start}
.cm-side{position:sticky;top:120px}.cm-side-card{background:linear-gradient(160deg,#1d1d1d,#252525);border:1px solid #353535;border-radius:18px;padding:16px;margin-bottom:12px}.cm-side-title{font-weight:900;font-size:15px;margin-bottom:10px}.cm-side-line{display:flex;gap:9px;align-items:center;padding:9px 0;color:#ccc;border-bottom:1px solid #303030}.cm-side-line:last-child{border-bottom:0}.cm-side-icon{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;background:#2c2c2c}
.cm-main{min-width:0}.cm-hero{padding:20px;background:linear-gradient(135deg,#252525,#181818);border:1px solid #393939;border-radius:20px;margin-bottom:14px;box-shadow:0 10px 30px rgba(0,0,0,.3)}.cm-hero h2{margin:0;font-size:24px}.cm-hero p{margin:5px 0 0;color:#aaa}.cm-card{background:linear-gradient(160deg,#202020,#282828);border:1px solid #383838;border-radius:18px;padding:15px;margin:12px 0}.cm-form{display:grid;gap:10px}.cm-form textarea,.cm-form input,.cm-form select{width:100%;background:#151515;color:#fff;border:1px solid #444;border-radius:12px;padding:12px;box-sizing:border-box;outline:none}.cm-form textarea{min-height:100px;resize:vertical}.cm-form textarea:focus,.cm-form input:focus,.cm-form select:focus{border-color:#ffd000;box-shadow:0 0 0 3px rgba(255,208,0,.12)}
.cm-composer-top{display:flex;gap:10px;align-items:center;margin-bottom:8px}.cm-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#ffd000;color:#111;font-weight:950;flex:0 0 auto}.cm-composer-label{font-weight:900}.cm-composer-sub{font-size:11px;color:#999}.cm-primary{width:100%;padding:13px;border:0;border-radius:12px;background:linear-gradient(135deg,#ffd000,#e6b800);color:#111;font-weight:950;letter-spacing:.2px}.cm-primary:disabled{opacity:.55}
.cm-feed-head{display:flex;justify-content:space-between;align-items:center;padding:8px 2px}.cm-feed-title{font-size:18px;font-weight:950}.cm-feed-note{font-size:11px;color:#888}.cm-post{padding:0;overflow:hidden}.cm-post-head{display:flex;gap:10px;align-items:center;padding:15px 15px 5px}.cm-post-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#2d2d2d;border:1px solid #444}.cm-author{font-size:14px;font-weight:900}.cm-muted{color:#999;font-size:11px}.cm-text{white-space:pre-wrap;line-height:1.6;font-size:15px;padding:6px 15px 12px}.cm-media,.cm-image{background:#090909;overflow:hidden;margin:0;border-top:1px solid #303030;border-bottom:1px solid #303030}.cm-media{aspect-ratio:16/9}.cm-media iframe{width:100%;height:100%;border:0}.cm-image img{display:block;width:100%;height:auto;max-height:680px;object-fit:contain}.cm-link{display:block;margin:0;padding:14px;border-top:1px solid #333;color:#ffd000;text-align:center;text-decoration:none}.cm-actions{display:flex;gap:8px;padding:10px 12px}.cm-actions button{flex:1}.cm-btn{padding:10px;border:1px solid #444;border-radius:11px;background:#242424;color:#ddd;font-weight:850}.cm-btn:hover{border-color:#ffd000;color:#ffd000}.cm-comments{border-top:1px solid #333;margin:0 12px 12px;padding:8px 2px}.cm-comment{padding:8px 5px;border-bottom:1px solid #2d2d2d;font-size:13px}.cm-comment-form{display:flex;gap:7px;margin-top:9px}.cm-comment-form input{flex:1}.cm-comment-form button{width:48px}.cm-empty,.cm-error{text-align:center;padding:35px 15px;color:#999}.cm-error{color:#ff6b60}.cm-store{text-align:center;padding:35px 10px}.cm-store-btn{display:block;padding:14px;background:#ffd000;color:#111;border-radius:12px;text-decoration:none;font-weight:950;margin-top:14px}.cm-image-file{font-size:13px;color:#ccc;padding:4px 0}.cm-image-file input{margin-top:6px}
@media(max-width:900px){.cm-layout{grid-template-columns:minmax(0,1fr);max-width:720px}.cm-side{display:none}.cm-tabs{top:64px;overflow:auto}.cm-tab{white-space:nowrap}.cm-hero h2{font-size:21px}}
@media(min-width:901px){.cm-main{grid-column:2}.cm-layout>.cm-side:last-child{grid-column:3;grid-row:1}.cm-layout>.cm-side:first-child{grid-column:1;grid-row:1}}
@media(max-width:600px){.cm-head{padding:8px 12px}.cm-title{font-size:18px}.cm-tabs{padding:8px 12px}.cm-layout{padding:12px 10px 45px}.cm-card{border-radius:16px}.cm-hero{border-radius:16px;padding:16px}.cm-post{border-radius:16px}.cm-text{font-size:14px}.cm-image img{max-height:520px}}
`;document.head.appendChild(s)}
function shell(){styles();if(modal)return modal;modal=document.createElement('div');modal.className='cm-overlay';modal.innerHTML=`<div class="cm-sheet"><div class="cm-head"><div class="cm-title">👥 Comunidade Entrega365<small>REDE SOCIAL DOS ENTREGADORES</small></div><button class="cm-close" aria-label="Fechar comunidade">×</button></div><div class="cm-tabs"><button class="cm-tab" data-v="community">👥 Comunidade</button><button class="cm-tab" data-v="marketplace">🛍️ Marketplace</button></div><div id="cm-content"></div></div>`;document.body.appendChild(modal);modal.querySelector('.cm-close').onclick=()=>modal.style.display='none';modal.querySelectorAll('.cm-tab').forEach(b=>b.onclick=()=>render(b.dataset.v));return modal}
async function render(v='community'){view=v;shell();modal.style.display='block';modal.querySelectorAll('.cm-tab').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='marketplace')return renderMarket();return renderCommunity()}
async function renderCommunity(){const c=modal.querySelector('#cm-content');c.innerHTML=`<div class="cm-layout"><aside class="cm-side"><div class="cm-side-card"><div class="cm-side-title">Comunidade</div><div class="cm-side-line"><span class="cm-side-icon">🏠</span><span>Feed de publicações</span></div><div class="cm-side-line"><span class="cm-side-icon">❤️</span><span>Interações</span></div><div class="cm-side-line"><span class="cm-side-icon">💬</span><span>Comentários</span></div></div><div class="cm-side-card"><div class="cm-side-title">Conecte-se</div><div class="cm-muted">Compartilhe experiências, dicas, rotas e novidades com outros entregadores.</div></div></aside><main class="cm-main"><section class="cm-hero"><h2>🚀 Bem-vindo à Comunidade</h2><p>Um espaço para os entregadores do Entrega365 conversarem, compartilharem e se ajudarem.</p></section><section class="cm-card cm-form"><div class="cm-composer-top"><div class="cm-avatar">365</div><div><div class="cm-composer-label">Nova publicação</div><div class="cm-composer-sub">Compartilhe algo com a comunidade</div></div></div><textarea id="cm-text" maxlength="4000" placeholder="O que você quer compartilhar?"></textarea><select id="cm-type"><option value="text">📝 Somente texto</option><option value="youtube">▶️ YouTube</option><option value="instagram">📸 Instagram</option><option value="image">🖼️ Imagem</option></select><input id="cm-url" type="url" placeholder="🔗 Link opcional"><label class="cm-image-file">📷 Adicionar imagem <input id="cm-image" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><button id="cm-publish" class="cm-primary">PUBLICAR NA COMUNIDADE</button></section><div class="cm-feed-head"><div class="cm-feed-title">Feed da comunidade</div><div class="cm-feed-note">Mais recentes primeiro</div></div><div id="cm-feed"><div class="cm-empty">Carregando publicações…</div></div></main><aside class="cm-side"><div class="cm-side-card"><div class="cm-side-title">💡 Ideias para postar</div><div class="cm-side-line">📍 Dicas de rota</div><div class="cm-side-line">💰 Experiências de ganhos</div><div class="cm-side-line">🏍️ Manutenção da moto</div><div class="cm-side-line">📱 Dicas do aplicativo</div></div></aside></div>`;modal.querySelector('#cm-publish').onclick=publish;modal.querySelector('#cm-image').onchange=()=>{if(modal.querySelector('#cm-image').files[0])modal.querySelector('#cm-type').value='image'};await loadPosts()}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!/^image\/(jpeg|png|webp|gif)$/i.test(file.type))return reject(new Error('Escolha uma imagem JPG, PNG, WEBP ou GIF.'));const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=1280;let w=img.naturalWidth,h=img.naturalHeight;if(w>max||h>max){const scale=Math.min(max/w,max/h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.72))};img.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));img.src=reader.result};reader.onerror=()=>reject(new Error('Não foi possível carregar a imagem.'));reader.readAsDataURL(file)})}
async function loadPosts(){try{const d=await api('/community/posts?limit=50');posts=d.posts||[];renderFeed()}catch(e){modal.querySelector('#cm-feed').innerHTML=`<div class="cm-error">Não foi possível carregar as publicações.<br>${esc(e.message)}</div>`}}
function renderFeed(){const el=modal.querySelector('#cm-feed');if(!posts.length){el.innerHTML='<div class="cm-empty">Ainda não há publicações. Seja o primeiro! 🚀</div>';return}el.innerHTML=posts.map(p=>`<article class="cm-card cm-post"><div class="cm-post-head"><div class="cm-post-avatar">👤</div><div><div class="cm-author">${esc(p.author_name||'Entregador')}</div><div class="cm-muted">${date(p.created_at)}</div></div></div><div class="cm-text">${esc(p.text||'')}</div>${media(p)}<div class="cm-actions"><button class="cm-btn" data-like="${p.id}">${p.liked?'❤️':'🤍'} ${p.like_count||0} Curtir</button><button class="cm-btn" data-comments="${p.id}">💬 ${p.comment_count||0} Comentar</button></div><div class="cm-comments" id="comments-${p.id}"></div></article>`).join('');el.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>like(Number(b.dataset.like)));el.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>comments(Number(b.dataset.comments)))}
async function publish(){const b=modal.querySelector('#cm-publish'),text=modal.querySelector('#cm-text').value.trim(),type=modal.querySelector('#cm-type').value,url=modal.querySelector('#cm-url').value.trim(),file=modal.querySelector('#cm-image').files[0];if(!text&&!url&&!file)return alert('Digite um texto, informe um link ou adicione uma imagem.');b.disabled=true;b.textContent='PUBLICANDO…';try{const image=await compressImage(file);const finalUrl=image||url;const finalType=image?'image':type;await api('/community/posts',{method:'POST',body:JSON.stringify({text,type:finalType,url:finalUrl})});modal.querySelector('#cm-text').value='';modal.querySelector('#cm-url').value='';modal.querySelector('#cm-image').value='';await loadPosts()}catch(e){alert('Não foi possível publicar: '+e.message)}finally{b.disabled=false;b.textContent='PUBLICAR NA COMUNIDADE'}}
async function like(id){const p=posts.find(x=>x.id===id);try{const d=await api('/community/likes',{method:p?.liked?'DELETE':'POST',body:JSON.stringify({postId:id})});if(p){p.liked=d.liked;p.like_count=d.likeCount}renderFeed()}catch(e){alert(e.message)}}
async function comments(id){const box=modal.querySelector('#comments-'+id);if(box.dataset.loaded==='1'){box.dataset.open=box.dataset.open==='1'?'0':'1';box.style.display=box.dataset.open==='1'?'block':'none';return}try{const d=await api('/community/comments?postId='+id);box.innerHTML=(d.comments||[]).map(x=>`<div class="cm-comment"><b>${esc(x.author_name)}</b><div>${esc(x.text)}</div></div>`).join('')+`<div class="cm-comment-form"><input id="comment-input-${id}" placeholder="Escreva um comentário"><button class="cm-primary" id="comment-btn-${id}">➤</button></div>`;box.dataset.loaded='1';box.dataset.open='1';box.querySelector('button').onclick=()=>addComment(id);box.style.display='block'}catch(e){box.innerHTML='<div class="cm-error">'+esc(e.message)+'</div>'}}
async function addComment(id){const input=modal.querySelector('#comment-input-'+id);if(!input?.value.trim())return;try{await api('/community/comments',{method:'POST',body:JSON.stringify({postId:id,text:input.value.trim()})});boxReload(id)}catch(e){alert(e.message)}}
async function boxReload(id){const box=modal.querySelector('#comments-'+id);if(!box)return;box.dataset.loaded='0';await comments(id)}
async function renderMarket(){const c=modal.querySelector('#cm-content');c.innerHTML='<div class="cm-layout"><main class="cm-main"><div class="cm-hero"><h2>🛍️ Marketplace Entrega365</h2><p>Loja configurada pelo backend PostgreSQL.</p></div><div class="cm-store"><div id="cm-store-action">Carregando…</div></div></main></div>'+(String(user()?.email||'').toLowerCase()===ADMIN?'<div class="cm-card cm-form" style="max-width:680px;margin:0 auto 30px"><input id="cm-store-url" placeholder="Link do Mercado Livre"><button id="cm-save" class="cm-primary">SALVAR LOJA</button></div>':'');try{const d=await api('/marketplace');const url=d.affiliateUrl||MARKET_DEFAULT;c.querySelector('#cm-store-action').innerHTML=`<a class="cm-store-btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">🛒 VISITAR LOJA</a>`;if(c.querySelector('#cm-store-url')){c.querySelector('#cm-store-url').value=url;c.querySelector('#cm-save').onclick=async()=>{try{await api('/marketplace',{method:'PUT',body:JSON.stringify({affiliateUrl:c.querySelector('#cm-store-url').value})});alert('Loja salva no PostgreSQL.');await renderMarket()}catch(e){alert(e.message)}}}}catch(e){c.querySelector('#cm-store-action').innerHTML='<div class="cm-error">'+esc(e.message)+'</div>'}}
function ensureButton(){styles();if(document.getElementById('e365-community-plus'))return;const actions=document.querySelector('header .actions'),tabs=document.querySelector('.tabs');const b=document.createElement('button');b.id='e365-community-plus';b.type='button';b.title='Comunidade Entrega365';b.innerHTML=actions?'👥':'<b>👥</b><span>Comunidade</span>';b.className=actions?'ico':'tab';b.onclick=()=>render('community');(actions||tabs)?.appendChild(b)}
const boot=()=>setTimeout(ensureButton,300);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.e365CommunityOpen=()=>render('community');window.e365MarketplaceOpen=()=>render('marketplace');