/* Entrega365 — Comunidade + Marketplace
   Conteúdo público entre usuários autenticados, persistido no Cloud Firestore.
   Vídeos são incorporados por URL (YouTube/Instagram), sem hospedar arquivos de vídeo no app.
*/
import { getFirestore, collection, addDoc, onSnapshot, query, orderBy, serverTimestamp, doc, setDoc, getDoc } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-firestore.js";
import { getApp } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-app.js";

const VERSION="1";
const POSTS="entrega365CommunityPosts";
const SETTINGS="entrega365CommunitySettings";
const INSTAGRAM="https://www.instagram.com/entrega365app/";
const MARKETPLACE_AFFILIATE="https://meli.la/1Komyrh";
const ADMIN_EMAILS=["entrega365.suporte@gmail.com"];
let db=null, unsubscribe=null, posts=[];
let modal=null, currentView="community", loaded=false, opening=false;

function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));}
function user(){return window.e365GetCurrentUser?.()||window.__e365Auth?.currentUser||null;}
function isAdmin(){return ADMIN_EMAILS.includes(String(user()?.email||"").toLowerCase());}
function dateText(v){try{const d=v?.toDate?v.toDate():new Date(v);if(!Number.isFinite(d.getTime()))return "Agora";return d.toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}catch{return "Agora"}}
function normalizeUrl(v){try{return new URL(v).href}catch{return ""}}
function youtubeId(url){const s=String(url||"");let m=s.match(/[?&]v=([^&#]+)/);if(m)return m[1];m=s.match(/youtu\.be\/([^?&#/]+)/);if(m)return m[1];m=s.match(/youtube\.com\/(?:shorts|embed)\/([^?&#/]+)/);return m?m[1]:""}
function instagramPath(url){try{const u=new URL(url);if(!/instagram\.com$/i.test(u.hostname.replace(/^www\./,"")))return "";const m=u.pathname.match(/^\/(?:reel|p|tv)\/([^/]+)/);return m?m[1]:""}catch{return ""}}
function mediaHtml(post){
  const url=normalizeUrl(post.url||"");
  if(!url)return "";
  const y=youtubeId(url);
  if(y)return '<div class="cm-media"><iframe src="https://www.youtube.com/embed/'+encodeURIComponent(y)+'" title="Vídeo do YouTube" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>';
  const ig=instagramPath(url);
  if(ig)return '<div class="cm-media cm-ig"><iframe src="https://www.instagram.com/'+(post.type==="instagram-reel"?'reel':'p')+'/'+encodeURIComponent(ig)+'/embed" title="Publicação do Instagram" loading="lazy" allowtransparency="true" frameborder="0"></iframe></div>';
  return '<a class="cm-link" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">🔗 Abrir conteúdo</a>';
}
function injectStyle(){
 if(document.getElementById("e365-community-style"))return;
 const s=document.createElement("style");s.id="e365-community-style";s.textContent=`
 .cm-overlay{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.72);backdrop-filter:blur(12px);display:flex;align-items:flex-end;justify-content:center}
 .cm-sheet{width:min(760px,100%);max-height:94dvh;overflow:auto;background:#171717;border:1px solid #363636;border-radius:24px 24px 0 0;box-shadow:0 -20px 60px rgba(0,0,0,.55);padding:14px 14px calc(22px + env(safe-area-inset-bottom))}
 .cm-head{position:sticky;top:0;z-index:3;background:#171717;padding:4px 0 12px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #2f2f2f}.cm-title{font-size:20px;font-weight:900}.cm-close{width:40px;height:40px;border:1px solid #383838;border-radius:12px;color:#fff;background:#222;font-size:20px}
 .cm-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.cm-tab{padding:11px;border:1px solid #383838;border-radius:12px;background:#222;color:#aaa;font-weight:900}.cm-tab.active{color:#ffd000;border-color:#ffd000;background:rgba(255,208,0,.08)}
 .cm-card{background:linear-gradient(160deg,#202020,#292929);border:1px solid #383838;border-radius:16px;padding:14px;margin:10px 0}.cm-card h3{margin:0 0 8px;font-size:15px}.cm-muted{color:#999;font-size:12px}.cm-form{display:grid;gap:9px}.cm-form textarea{width:100%;min-height:82px;resize:vertical;background:#151515;color:#fff;border:1px solid #3d3d3d;border-radius:11px;padding:11px;outline:none}.cm-form textarea:focus,.cm-form input:focus{border-color:#ffd000;box-shadow:0 0 0 3px rgba(255,208,0,.12)}.cm-form select,.cm-form input{width:100%;background:#151515;color:#fff;border:1px solid #3d3d3d;border-radius:11px;padding:11px;outline:none}.cm-primary{width:100%;padding:12px;border-radius:11px;background:linear-gradient(135deg,#ffd000,#e6b800);color:#111;font-weight:900}.cm-primary:disabled{opacity:.55}.cm-post{position:relative}.cm-author{display:flex;align-items:center;gap:9px;margin-bottom:9px}.cm-avatar{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:#ffd000;color:#111;font-weight:900}.cm-author strong{font-size:13px}.cm-post-text{white-space:pre-wrap;line-height:1.5;margin:7px 0 10px}.cm-media{position:relative;aspect-ratio:16/9;background:#090909;border-radius:12px;overflow:hidden;margin:10px 0}.cm-media iframe{width:100%;height:100%;border:0}.cm-ig{aspect-ratio:auto;min-height:420px}.cm-ig iframe{min-height:420px}.cm-link{display:block;padding:12px;border:1px solid #444;border-radius:10px;color:#ffd000;text-decoration:none;text-align:center;font-weight:800}.cm-actions{display:flex;gap:8px;margin-top:9px}.cm-actions button{flex:1;padding:9px;border:1px solid #3c3c3c;border-radius:10px;background:#222;color:#ddd}.cm-comments{border-top:1px solid #353535;margin-top:12px;padding-top:10px}.cm-comment{padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05)}.cm-comment:last-child{border:0}.cm-comment b{font-size:12px}.cm-comment p{margin:2px 0;color:#ddd;font-size:13px;white-space:pre-wrap}.cm-comment-form{display:flex;gap:7px;margin-top:8px}.cm-comment-form input{flex:1}.cm-comment-form button{width:46px;border-radius:10px;background:#ffd000;color:#111;font-weight:900}.cm-empty{text-align:center;padding:28px 10px;color:#999}.cm-store{display:grid;gap:12px;text-align:center;padding:24px 14px}.cm-store-icon{font-size:46px}.cm-store h2{margin:0;font-size:24px}.cm-store p{margin:0;color:#aaa}.cm-store-btn{display:block;text-decoration:none;padding:14px;border-radius:12px;background:linear-gradient(135deg,#ffd000,#e6b800);color:#111;font-weight:900}.cm-admin{border-top:1px solid #383838;margin-top:14px;padding-top:14px;text-align:left}.cm-smallbtn{padding:9px 11px;border:1px solid #444;border-radius:10px;background:#222;color:#fff;font-weight:800}.cm-error{color:#ff6b60;background:rgba(255,69,58,.08);border:1px solid rgba(255,69,58,.25);border-radius:10px;padding:10px;font-size:12px;margin:8px 0}
 .cm-plus{border-color:#ffd000!important;color:#ffd000!important;font-size:22px!important;font-weight:900!important}.cm-plus-label{font-size:10px;font-weight:900;display:block;line-height:1}
 `;document.head.appendChild(s);
}
function ensureButton(){
 injectStyle();
 if(document.getElementById("e365-community-plus"))return;
 const actions=document.querySelector("header .actions");
 if(actions){const b=document.createElement("button");b.id="e365-community-plus";b.className="ico cm-plus";b.type="button";b.title="Comunidade e Marketplace";b.setAttribute("aria-label","Comunidade e Marketplace");b.innerHTML="+";b.onclick=()=>openModal("community");actions.appendChild(b);return;}
 const tabs=document.querySelector(".tabs");
 if(tabs){const b=document.createElement("button");b.id="e365-community-plus";b.className="tab cm-plus";b.type="button";b.innerHTML='<b>+</b><span class="cm-plus-label">MAIS</span>';b.onclick=()=>openModal("community");tabs.appendChild(b);}
}
function shell(){
 if(modal)return modal;
 modal=document.createElement("div");modal.className="cm-overlay";modal.id="e365-community-modal";modal.innerHTML='<div class="cm-sheet"><div class="cm-head"><div class="cm-title">＋ Entrega365</div><button class="cm-close" type="button">×</button></div><div class="cm-tabs"><button class="cm-tab" data-view="community">👥 Comunidade</button><button class="cm-tab" data-view="marketplace">🛍️ Marketplace</button></div><div id="cm-content"></div></div>';
 document.body.appendChild(modal);modal.querySelector(".cm-close").onclick=closeModal;modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});modal.querySelectorAll(".cm-tab").forEach(b=>b.onclick=()=>renderView(b.dataset.view));return modal;
}
async function initDb(){if(db)return db;try{db=getFirestore(getApp());return db}catch(e){console.warn("Entrega365 Community Firestore:",e);return null}}
async function openModal(view="community"){
 if(opening)return;shell();opening=true;currentView=view;modal.style.display="flex";renderLoading();await initDb();opening=false;renderView(view);}
function closeModal(){if(modal)modal.style.display="none"}
function renderLoading(){const c=modal?.querySelector("#cm-content");if(c)c.innerHTML='<div class="cm-card cm-empty">Carregando comunidade…</div>'}
function renderView(view){currentView=view;if(!modal)return;modal.querySelectorAll(".cm-tab").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(view==="marketplace")renderMarketplace();else renderCommunity();}
function renderCommunity(){
 const c=modal.querySelector("#cm-content");
 c.innerHTML='<div class="cm-card"><h3>📣 Comunidade Entrega365</h3><div class="cm-muted">Compartilhe dicas, novidades, vídeos e experiências com outros entregadores.</div></div><div class="cm-card"><h3>✍️ Nova publicação</h3><div class="cm-form"><textarea id="cm-text" maxlength="1200" placeholder="O que você quer compartilhar?"></textarea><select id="cm-type"><option value="text">Somente texto</option><option value="youtube">YouTube</option><option value="instagram-reel">Instagram / Reel</option></select><input id="cm-url" type="url" placeholder="Cole o link do vídeo (opcional)"><button id="cm-publish" class="cm-primary">PUBLICAR NA COMUNIDADE</button></div><div class="cm-muted" style="margin-top:8px">O link é incorporado no post. Vídeos continuam hospedados no YouTube/Instagram.</div></div><div id="cm-feed"></div>';
 c.querySelector("#cm-type").onchange=e=>{c.querySelector("#cm-url").placeholder=e.target.value==="text"?"Link opcional":"Cole o link do vídeo"};
 c.querySelector("#cm-publish").onclick=publishPost;renderFeed();subscribePosts();
}
function renderMarketplace(){
 const c=modal.querySelector("#cm-content");
 c.innerHTML='<div class="cm-store"><div class="cm-store-icon">🛍️</div><h2>Marketplace Entrega365</h2><p>Produtos selecionados para quem trabalha com entregas. A loja será aberta no Mercado Livre.</p><div id="cm-store-action"></div><div class="cm-muted">Os links podem ser de produtos ou de uma loja afiliada.</div></div>'+(isAdmin()?'<div class="cm-card cm-admin"><h3>⚙️ Configuração da loja</h3><div class="cm-form"><input id="cm-store-url" type="url" placeholder="Cole aqui o link da sua loja afiliada no Mercado Livre"><button id="cm-save-store" class="cm-primary">SALVAR LOJA</button><div class="cm-muted">Esta configuração fica disponível para todos os usuários.</div></div></div>':'');loadStoreSetting();if(isAdmin())modal.querySelector("#cm-save-store").onclick=saveStoreSetting;
}
async function loadStoreSetting(){const action=modal?.querySelector("#cm-store-action");if(!action)return;let url=localStorage.getItem("entrega365:marketplaceUrl")||MARKETPLACE_AFFILIATE;try{const d=await getDoc(doc(await initDb(),SETTINGS,"marketplace"));if(d.exists()&&d.data()?.url)url=d.data().url;}catch(e){console.warn("Marketplace setting read:",e)}if(modal?.querySelector("#cm-store-url"))modal.querySelector("#cm-store-url").value=url;if(url)action.innerHTML='<a class="cm-store-btn" href="'+esc(normalizeUrl(url))+'" target="_blank" rel="noopener noreferrer">🛒 VISITAR LOJA NO MERCADO LIVRE</a>';else action.innerHTML='<div class="cm-muted">A loja ainda está sendo configurada.</div>'}
async function saveStoreSetting(){const input=modal?.querySelector("#cm-store-url"),url=normalizeUrl(input?.value||"");if(!url||!/mercadolivre|mercadolibre/i.test(url)){alert("Cole um link válido do Mercado Livre.");return}try{await setDoc(doc(await initDb(),SETTINGS,"marketplace"),{url,updatedAt:serverTimestamp(),updatedBy:user()?.uid||""},{merge:true});localStorage.setItem("entrega365:marketplaceUrl",url);await loadStoreSetting();alert("Loja salva e disponível para todos os usuários.");}catch(e){console.error(e);alert("Não foi possível salvar a loja. Verifique a conexão com a comunidade.");}}
function subscribePosts(){if(unsubscribe)unsubscribe();if(!db){renderFeedError("A comunidade não conseguiu conectar ao Firestore.");return}try{const q=query(collection(db,POSTS),orderBy("createdAt","desc"));unsubscribe=onSnapshot(q,snap=>{posts=snap.docs.map(d=>({id:d.id,...d.data()}));renderFeed()},e=>{console.warn("Community listener:",e);renderFeedError("Não foi possível carregar as publicações. Verifique as regras do Firestore.")});loaded=true}catch(e){renderFeedError("Não foi possível iniciar a comunidade.")}}
function renderFeedError(msg){const el=modal?.querySelector("#cm-feed");if(el)el.innerHTML='<div class="cm-error">'+esc(msg)+'</div>'}
function renderFeed(){const el=modal?.querySelector("#cm-feed");if(!el||currentView!=="community")return;if(!posts.length){el.innerHTML='<div class="cm-card cm-empty">Ainda não há publicações.<br>Seja o primeiro a publicar! 🚀</div>';return}el.innerHTML=posts.map(renderPost).join("");el.querySelectorAll("[data-comment]").forEach(b=>b.onclick=()=>addComment(b.dataset.comment));}
function renderPost(p){const name=esc(p.authorName||p.authorEmail||"Entregador");const avatar=esc((p.authorName||p.authorEmail||"E").trim().slice(0,1).toUpperCase());const media=p.type!=="text"&&p.url?mediaHtml(p):"";return '<article class="cm-card cm-post" data-post="'+esc(p.id)+'"><div class="cm-author"><div class="cm-avatar">'+avatar+'</div><div><strong>'+name+'</strong><div class="cm-muted">'+dateText(p.createdAt)+'</div></div></div>'+(p.text?'<div class="cm-post-text">'+esc(p.text)+'</div>':'')+media+'<div class="cm-actions"><button type="button" data-comment="'+esc(p.id)+'">💬 Comentar</button><a class="cm-link" style="padding:9px;text-decoration:none" href="'+esc(normalizeUrl(p.url||""))+'" target="_blank" rel="noopener noreferrer">↗ Abrir</a></div><div class="cm-comments" id="comments-'+esc(p.id)+'"><div class="cm-muted">Carregando comentários…</div></div></article>'}
async function publishPost(){const text=modal.querySelector("#cm-text").value.trim();const type=modal.querySelector("#cm-type").value;const url=normalizeUrl(modal.querySelector("#cm-url").value.trim());if(!text&&!url){alert("Escreva uma publicação ou cole um vídeo.");return}if(type!=="text"&&!url){alert("Cole o link do vídeo.");return}if(type==="youtube"&&!youtubeId(url)){alert("Cole um link válido do YouTube.");return}if(type==="instagram-reel"&&!instagramPath(url)){alert("Cole um link válido do Instagram.");return}const u=user();if(!u){alert("Entre com sua conta Google para publicar.");return}const b=modal.querySelector("#cm-publish");b.disabled=true;b.textContent="PUBLICANDO…";try{await addDoc(collection(await initDb(),POSTS),{text,type,url,authorUid:u.uid,authorName:u.displayName||u.email||"Entregador",authorEmail:u.email||"",createdAt:serverTimestamp(),version:VERSION});modal.querySelector("#cm-text").value="";modal.querySelector("#cm-url").value="";alert("Publicação enviada para a comunidade!");}catch(e){console.error("Community publish:",e);alert("Não foi possível publicar. Verifique as permissões do Firestore.");}finally{b.disabled=false;b.textContent="PUBLICAR NA COMUNIDADE"}}
async function addComment(postId){const article=modal?.querySelector('[data-post="'+CSS.escape(postId)+'"]');if(!article)return;let box=article.querySelector(".cm-comment-form");if(!box){const comments=article.querySelector(".cm-comments");box=document.createElement("div");box.className="cm-comment-form";box.innerHTML='<input maxlength="500" placeholder="Escreva um comentário…"><button type="button">➤</button>';comments.appendChild(box);box.querySelector("input").focus();box.querySelector("button").onclick=()=>submitComment(postId,box)}else{box.querySelector("input").focus()}}
async function submitComment(postId,box){const input=box.querySelector("input"),text=input.value.trim(),u=user();if(!text||!u)return;const b=box.querySelector("button");b.disabled=true;try{await addDoc(collection(await initDb(),POSTS,postId,"comments"),{text,authorUid:u.uid,authorName:u.displayName||u.email||"Entregador",authorEmail:u.email||"",createdAt:serverTimestamp()});input.value="";await loadComments(postId)}catch(e){console.error("Community comment:",e);alert("Não foi possível comentar. Verifique as permissões do Firestore.")}finally{b.disabled=false}}
async function loadComments(postId){const box=modal?.querySelector('[data-post="'+CSS.escape(postId)+'"] .cm-comments');if(!box)return;try{const q=query(collection(await initDb(),POSTS,postId,"comments"),orderBy("createdAt","asc"));onSnapshot(q,snap=>{const old=box.querySelector(".cm-comment-form");box.innerHTML=snap.docs.map(d=>{const x=d.data();return '<div class="cm-comment"><b>'+esc(x.authorName||"Entregador")+'</b><span class="cm-muted"> · '+dateText(x.createdAt)+'</span><p>'+esc(x.text||"")+'</p></div>'}).join("")+(old?old.outerHTML:"")||'<div class="cm-muted">Nenhum comentário ainda.</div>';if(old){const f=box.querySelector(".cm-comment-form");f.querySelector("button").onclick=()=>submitComment(postId,f)}},()=>{box.innerHTML='<div class="cm-muted">Comentários indisponíveis.</div>'})}catch(e){box.innerHTML='<div class="cm-muted">Comentários indisponíveis.</div>'}}

const observer=new MutationObserver(()=>ensureButton());observer.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener("load",ensureButton);window.addEventListener("e365-data-changed",ensureButton);
setTimeout(ensureButton,500);setTimeout(ensureButton,2000);
window.e365Community={open:openModal,close:closeModal,refresh:()=>renderView(currentView)};
