import { GoogleAuthProvider, reauthenticateWithPopup } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-auth.js";
const SCOPE="https://www.googleapis.com/auth/drive.file",API="https://www.googleapis.com/drive/v3/files",UP="https://www.googleapis.com/upload/drive/v3/files",FOLDER="Entrega365",NAME="entrega365-backup.json",TK="entrega365:driveAccessToken",TE="entrega365:driveAccessTokenExp";
export function initDriveBackup(auth){if(!auth||window.__e365Drive)return;window.__e365Drive=true;let token="",exp=0,fileId="",busy=false,restoring=false;
const session=()=>localStorage.getItem("dcv2:session")||"",mail=()=>localStorage.getItem("entrega365:email")||"";
const load=()=>{const t=localStorage.getItem(TK)||"",e=+localStorage.getItem(TE)||0;if(t&&e>Date.now()+60000){token=t;exp=e;return true}return false};
const put=(t,e)=>{token=t;exp=e;localStorage.setItem(TK,t);localStorage.setItem(TE,String(e))};
async function tok(interactive=false){if(token&&Date.now()<exp-60000)return token;if(load())return token;if(!interactive)throw Error("drive_authorization_required");const u=auth.currentUser;if(!u)throw Error("login_required");const p=new GoogleAuthProvider();p.addScope(SCOPE);p.setCustomParameters({login_hint:mail()||undefined,prompt:"consent"});const z=await reauthenticateWithPopup(u,p),q=GoogleAuthProvider.credentialFromResult(z);if(!q?.accessToken)throw Error("drive_token");put(q.accessToken,Date.now()+3500000);return token}
async function api(url,opt={}){const t=await tok(false),x=await fetch(url,{...opt,cache:"no-store",headers:{Authorization:"Bearer "+t,...(opt.headers||{})}});if(!x.ok)throw Error("drive_"+x.status);return x.status===204?null:x.json()}
async function folder(){const q="name='"+FOLDER+"' and mimeType='application/vnd.google-apps.folder' and trashed=false",x=await api(API+"?q="+encodeURIComponent(q)+"&spaces=drive&fields=files(id)&pageSize=10");if(x.files?.[0])return x.files[0].id;return (await api(API+"?fields=id",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:FOLDER,mimeType:"application/vnd.google-apps.folder"})})).id}
async function find(p){const q="'"+p+"' in parents and name='"+NAME+"' and trashed=false",x=await api(API+"?q="+encodeURIComponent(q)+"&spaces=drive&fields=files(id,modifiedTime)&pageSize=10");return x.files?.[0]||null}
function snap(){const o={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith("dcv2:"))o[k]=localStorage.getItem(k)}return{format:"Entrega365Backup",version:12,session:session(),email:mail(),localStorage:o,exportedAt:new Date().toISOString()}}
async function save(){if(busy||!session()||restoring)return;busy=true;try{const p=await folder(),old=fileId?{id:fileId}:await find(p),b="----E365"+Date.now(),body=new Blob(["--"+b+"\r\nContent-Type: application/json\r\n\r\n",JSON.stringify(old?{name:NAME,mimeType:"application/json"}:{name:NAME,mimeType:"application/json",parents:[p]}),"\r\n--"+b+"\r\nContent-Type: application/json\r\n\r\n",JSON.stringify(snap()),"\r\n--"+b+"--"]);const z=await api((old?UP+"/"+old.id:UP)+"?uploadType=multipart&fields=id",{method:old?"PATCH":"POST",headers:{"Content-Type":"multipart/related; boundary="+b},body});fileId=z.id}catch(e){console.warn("Drive save:",e)}finally{busy=false}}
async function restore(){if(!session()||restoring)return false;restoring=true;try{const p=await folder(),old=await find(p);if(!old)return false;fileId=old.id;const t=await tok(false),x=await fetch(API+"/"+old.id+"?alt=media",{cache:"no-store",headers:{Authorization:"Bearer "+t}});if(!x.ok)throw Error("drive_"+x.status);const d=await x.json();if(d.format!=="Entrega365Backup"||!d.localStorage)throw Error("invalid_backup");for(const k of Object.keys(d.localStorage))localStorage.setItem(k,d.localStorage[k]);if(d.session)localStorage.setItem("dcv2:session",d.session);if(d.email)localStorage.setItem("entrega365:email",d.email);return true}catch(e){console.warn("Drive restore:",e);return false}finally{restoring=false}}
let timer=0;const queue=()=>{clearTimeout(timer);timer=setTimeout(save,700)};
window.entrega365DriveAutoSync=async()=>{if(!session())return;const ok=await restore();if(ok)window.render?.();await save()};
window.addEventListener("e365-data-changed",queue);setInterval(()=>{if(session())save()},30000);setTimeout(()=>window.entrega365DriveAutoSync(),700)}
