/* Entrega365 PRO — painel e assinatura */
(function(){
  const PLAN_KEY='entrega365:plan',SUB_KEY='entrega365:subscriptionId';
  const PRICE='R$ 9,90',PAYMENT_LINK='https://mpago.la/2Zg7Yyc',ADMIN_EMAIL='andermuchael@gmail.com';
  const valid=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim());
  function email(){const a=(localStorage.getItem('entrega365:email')||'').trim().toLowerCase();return valid(a)?a:''}
  function isAdmin(){return email()===ADMIN_EMAIL}
  function getPlan(){return isAdmin()?'active':(localStorage.getItem(PLAN_KEY)||'free')}
  function setPlan(v){if(!isAdmin())localStorage.setItem(PLAN_KEY,v)}
  function sub(){return localStorage.getItem(SUB_KEY)||''}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function css(){if(document.getElementById('e365procss'))return;const s=document.createElement('style');s.id='e365procss';s.textContent=`
  .e365probtn{position:relative!important;color:#111!important;background:linear-gradient(135deg,#ffd000,#f2b800)!important;border-color:#ffd000!important;font-weight:900!important}
  .e365probadge{position:absolute;top:-6px;right:-4px;background:#111;color:#ffd000;border:1px solid #ffd000;border-radius:999px;padding:1px 5px;font-size:8px;font-weight:900}
  .e365prohero{background:linear-gradient(145deg,#292100,#1d1d1d 60%);border:1px solid rgba(255,208,0,.45);border-radius:20px;padding:20px;margin-bottom:14px;box-shadow:0 10px 30px rgba(0,0,0,.35)}
  .e365protitle{font-size:24px;font-weight:950;color:#fff}.e365proprice{font-size:29px;font-weight:950;color:#ffd000;margin:7px 0}.e365proprice span{font-size:13px;color:#aaa;font-weight:600}
  .e365protag{display:inline-block;padding:5px 9px;border-radius:999px;background:#ffd000;color:#111;font-size:10px;font-weight:950;margin-bottom:10px}
  .e365prostatus{padding:10px 12px;border-radius:12px;background:rgba(255,208,0,.08);border:1px solid rgba(255,208,0,.25);font-size:12px;margin-top:10px}
  .e365proactions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.e365proactions button{padding:13px;border-radius:12px;font-weight:900}.e365proprimary{background:#ffd000;color:#111}.e365prosecondary{border:1px solid #444;background:#222;color:#fff}
  .e365profeatures{display:grid;grid-template-columns:1fr 1fr;gap:10px}.e365profeature{padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel);cursor:pointer}.e365profeature:active{transform:scale(.98)}.e365profeature b{display:block;margin-bottom:4px}.e365profeature span{font-size:11px;color:var(--muted)}
  .e365pronote{font-size:11px;color:var(--muted);line-height:1.45;margin-top:12px}.e365profree{border:1px solid var(--line);background:var(--panel);border-radius:16px;padding:15px;margin-bottom:14px}.e365protable{width:100%;border-collapse:collapse;font-size:12px}.e365protable td{padding:9px 5px;border-bottom:1px solid var(--line)}.e365protable td:last-child{text-align:right;font-weight:900;color:#ffd000}
  @media(max-width:390px){.e365profeatures,.e365proactions{grid-template-columns:1fr}.e365protitle{font-size:22px}}
  `;document.head.appendChild(s)}
  function panel(){
    const active=getPlan()==='active',mail=email();
    return `<div class="e365prohero"><div class="e365protag">ENTREGA365 PRO</div><div class="e365protitle">Seu painel profissional</div><div class="e365proprice">${PRICE} <span>/ mês</span></div><div class="muted">Mais controle para trabalhar com vários clientes e estabelecimentos.</div><div class="e365prostatus">Status: <b>${active?'PRO ATIVO':'PLANO GRATUITO'}</b>${mail?`<br><span class="small">Conta: ${esc(mail)}</span>`:''}</div>${active?`<div class="e365proactions"><button class="e365proprimary" id="e365procheck">ATUALIZAR STATUS</button><button class="e365prosecondary" id="e365proclose">VOLTAR</button></div>`:`<div class="e365proactions"><button class="e365proprimary" id="e365probuy">ASSINAR POR R$ 9,90</button><button class="e365prosecondary" id="e365prolegacy">PAGAR PELO MERCADO PAGO</button></div>`}</div>
    <div class="card"><div class="title">⭐ Recursos PRO</div><div class="e365profeatures"><button class="e365profeature" id="e365estopen"><b>🏪 Vários estabelecimentos</b><span>Crie e alterne entre empresas e clientes.</span></button><button class="e365profeature" id="e365report"><b>📊 Relatórios avançados</b><span>Resumo de entregas, ganhos e despesas.</span></button><button class="e365profeature" id="e365export"><b>📄 Exportar dados</b><span>Exporte seus registros para guardar.</span></button><button class="e365profeature" id="e365backup"><b>☁️ Backup</b><span>Proteja seus dados no Google Drive.</span></button><button class="e365profeature" id="e365ads"><b>🚫 Sem anúncios</b><span>Experiência PRO limpa.</span></button><button class="e365profeature" id="e365security"><b>🔐 Conta PRO</b><span>Recursos profissionais habilitados.</span></button></div></div>
    <div class="e365profree"><div class="title">🆓 Comparação</div><table class="e365protable"><tr><td>Controle diário</td><td>✓</td></tr><tr><td>Gastos e mecânica</td><td>✓</td></tr><tr><td>Agenda e calculadora</td><td>✓</td></tr><tr><td>Vários estabelecimentos</td><td>${active?'✓ PRO':'PRO'}</td></tr><tr><td>Relatórios avançados</td><td>${active?'✓ PRO':'PRO'}</td></tr><tr><td>Exportações</td><td>${active?'✓ PRO':'PRO'}</td></tr><tr><td>Sem anúncios</td><td>${active?'✓ PRO':'PRO'}</td></tr></table></div>`;
  }
  function fallback(){
    let m=document.getElementById('e365profallback');if(m)m.remove();m=document.createElement('div');m.id='e365profallback';m.style.cssText='position:fixed;inset:0;z-index:99999;overflow:auto;background:#121212;padding:18px 12px 100px';m.innerHTML='<main style="max-width:600px;margin:auto"><button id="e365proback" style="padding:10px 14px;border:1px solid #444;border-radius:10px;background:#222;color:#fff;font-weight:800;margin-bottom:12px">← Voltar</button>'+panel()+'</main>';document.body.appendChild(m);bind(m);m.querySelector('#e365proback').onclick=()=>m.remove()
  }
  async function readJson(r){const raw=await r.text();try{return raw?JSON.parse(raw):{}}catch{throw new Error('Servidor não retornou JSON (HTTP '+r.status+').')}}
  async function status(){const mail=email();if(!mail)throw new Error('Entre com um e-mail válido para verificar o PRO.');if(isAdmin()){setPlan('active');return{active:true,admin:true}}const r=await fetch('/api/pro-status?email='+encodeURIComponent(mail)+(sub()?'&subscription_id='+encodeURIComponent(sub()):''),{cache:'no-store'}),d=await readJson(r);if(!r.ok)throw new Error(d.message||'Não foi possível consultar a assinatura.');if(d.subscription_id)localStorage.setItem(SUB_KEY,String(d.subscription_id));setPlan(d.active?'active':'free');return d}
  async function buy(){const mail=email();if(!mail)return alert('Entre usando seu e-mail antes de assinar.');try{const r=await fetch('/api/pro-checkout',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email:mail}),cache:'no-store'}),d=await readJson(r);if(!r.ok||!d.init_point)throw new Error(d.message||'Não foi possível iniciar a assinatura.');if(d.subscription_id)localStorage.setItem(SUB_KEY,String(d.subscription_id));location.href=d.init_point}catch(e){alert(e.message)}}
  function report(){const u=localStorage.getItem('dcv2:session')||'';let days=0,entries=0,earn=0,exp=0;for(let i=0;i<366;i++){const d=new Date();d.setDate(d.getDate()-i);const k='dcv2:'+u+':day:'+d.toISOString().slice(0,10);try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x){days++;(x.entries||[]).forEach(e=>{entries++;earn+=Number(e.valor||e.value||e.total||0)||0})}}catch{}}alert('RELATÓRIO PRO\n\nDias registrados: '+days+'\nEntregas lançadas: '+entries+'\nGanhos encontrados: '+earn.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}))}
  function exportData(){const u=localStorage.getItem('dcv2:session')||'';const data={exportadoEm:new Date().toISOString(),usuario:email(),dados:{}};Object.keys(localStorage).filter(k=>k.startsWith('dcv2:'+u+':')).forEach(k=>data.dados[k]=localStorage.getItem(k));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='entrega365-pro-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function bind(root=document){root.querySelector('#e365probuy')?.addEventListener('click',buy);root.querySelector('#e365prolegacy')?.addEventListener('click',()=>window.open(PAYMENT_LINK,'_blank','noopener,noreferrer'));root.querySelector('#e365procheck')?.addEventListener('click',async()=>{try{const d=await status();alert(d.active?'Assinatura PRO ativa.':'Assinatura ainda não autorizada.');open()}catch(e){alert(e.message)}});root.querySelector('#e365estopen')?.addEventListener('click',()=>window.e365Establishments?.openNew?window.e365Establishments.openNew():alert('Recurso de estabelecimentos carregando.'));root.querySelector('#e365report')?.addEventListener('click',report);root.querySelector('#e365export')?.addEventListener('click',exportData);root.querySelector('#e365backup')?.addEventListener('click',()=>alert('O backup no Google Drive está disponível na função de backup do aplicativo.'));root.querySelector('#e365ads')?.addEventListener('click',()=>alert('PRO: anúncios desativados para esta conta.'));root.querySelector('#e365security')?.addEventListener('click',()=>alert('Conta PRO reconhecida e recursos profissionais habilitados.'));root.querySelector('#e365proclose')?.addEventListener('click',()=>window.go?.('day'))}
  function open(){css();if(typeof window.shell==='function'){window.shell(panel());bind()}else fallback()}
  async function install(){css();const actions=document.querySelector('.actions');if(actions&&!actions.querySelector('.e365probtn')){const b=document.createElement('button');b.className='ico e365probtn';b.title='Entrega365 PRO';b.innerHTML='PRO<span class="e365probadge">+</span>';b.onclick=open;actions.prepend(b)}const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-pro]')){const b=document.createElement('button');b.className='tab';b.dataset.pro='1';b.innerHTML='<b>⭐</b>PRO';b.onclick=open;tabs.appendChild(b)}if(isAdmin())setPlan('active')}
  window.e365Pro=open;window.e365ProStatus=status;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,250));else setTimeout(install,250);setInterval(install,3000);
})();
