/* Entrega365 PRO — primeira camada de monetização/UI */
(function(){
  const KEY='entrega365:plan';
  const getPlan=()=>localStorage.getItem(KEY)||'free';
  const css=()=>{if(document.getElementById('e365procss'))return;const s=document.createElement('style');s.id='e365procss';s.textContent=`
  .e365probtn{position:relative!important;color:#111!important;background:linear-gradient(135deg,#ffd000,#f2b800)!important;border-color:#ffd000!important;font-weight:900!important}
  .e365probadge{position:absolute;top:-6px;right:-4px;background:#111;color:#ffd000;border:1px solid #ffd000;border-radius:999px;padding:1px 5px;font-size:8px;font-weight:900}
  .e365prohero{background:linear-gradient(145deg,#292100,#1d1d1d 60%);border:1px solid rgba(255,208,0,.45);border-radius:20px;padding:22px;margin-bottom:14px;box-shadow:0 10px 30px rgba(0,0,0,.35)}
  .e365protitle{font-size:25px;font-weight:950;color:#fff}.e365proprice{font-size:30px;font-weight:950;color:#ffd000;margin:8px 0}.e365proprice span{font-size:13px;color:#aaa;font-weight:600}
  .e365protag{display:inline-block;padding:5px 9px;border-radius:999px;background:#ffd000;color:#111;font-size:10px;font-weight:950;margin-bottom:10px}
  .e365progrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.e365proitem{padding:13px;border:1px solid var(--line);border-radius:13px;background:var(--panel)}.e365proitem b{display:block;margin-bottom:3px}.e365proitem span{font-size:11px;color:var(--muted)}
  .e365protable{width:100%;border-collapse:collapse;font-size:12px}.e365protable td{padding:10px 5px;border-bottom:1px solid var(--line)}.e365protable td:last-child{text-align:right;font-weight:900;color:#ffd000}
  .e365pronote{font-size:11px;color:var(--muted);line-height:1.45;margin-top:12px}.e365profree{border:1px solid var(--line);background:var(--panel);border-radius:16px;padding:15px;margin-bottom:14px}
  @media(max-width:390px){.e365progrid{grid-template-columns:1fr}.e365protitle{font-size:22px}}
  `;document.head.appendChild(s)};
  function screen(){return `<div class="e365prohero"><div class="e365protag">ENTREGA365 PRO</div><div class="e365protitle">Trabalhe mais. Controle melhor.</div><div class="e365proprice">R$ 9,90 <span>/ mês</span></div><div class="muted">Recursos profissionais para quem faz entregas todos os dias.</div><button class="primary" id="e365probuy">QUERO O PRO</button><div class="e365pronote">A cobrança será habilitada nesta etapa. O botão não realiza nenhuma cobrança agora.</div></div><div class="card"><div class="title">⭐ O que entra no PRO</div><div class="e365progrid"><div class="e365proitem"><b>🏪 Vários estabelecimentos</b><span>Separe os dados de cada cliente ou empresa.</span></div><div class="e365proitem"><b>☁️ Backup automático</b><span>Mais praticidade para proteger seus dados.</span></div><div class="e365proitem"><b>📊 Relatórios avançados</b><span>Veja ganhos, entregas, gastos e histórico.</span></div><div class="e365proitem"><b>📄 Exportações</b><span>PDF e planilhas para seus registros.</span></div><div class="e365proitem"><b>🚫 Sem anúncios</b><span>Experiência limpa durante o trabalho.</span></div><div class="e365proitem"><b>🔐 Recursos profissionais</b><span>Mais controle sobre seus dados e perfis.</span></div></div></div><div class="e365profree"><div class="title">🆓 Versão gratuita</div><table class="e365protable"><tr><td>Controle diário</td><td>✓</td></tr><tr><td>Gastos e mecânica</td><td>✓</td></tr><tr><td>Agenda e calculadora</td><td>✓</td></tr><tr><td>Backup no Google Drive</td><td>✓</td></tr><tr><td>Vários estabelecimentos</td><td>PRO</td></tr><tr><td>Relatórios avançados</td><td>PRO</td></tr><tr><td>Sem anúncios</td><td>PRO</td></tr></table></div>`}
  function bind(){document.getElementById('e365probuy')?.addEventListener('click',()=>alert('O Entrega365 PRO já está preparado. A próxima etapa é conectar o pagamento para ativar a assinatura automaticamente.'))}
  function open(){css();if(typeof window.shell==='function'){window.shell(screen());bind()}else setTimeout(open,100)}
  function install(){css();const actions=document.querySelector('.actions');if(actions&&!actions.querySelector('.e365probtn')){const b=document.createElement('button');b.className='ico e365probtn';b.title='Entrega365 PRO';b.innerHTML='PRO<span class="e365probadge">+</span>';b.onclick=open;actions.prepend(b)}const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-pro]')){const b=document.createElement('button');b.className='tab';b.dataset.pro='1';b.innerHTML='<b>⭐</b>PRO';b.onclick=open;tabs.appendChild(b)}}
  window.e365Pro=open;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,150));else setTimeout(install,150);
  setInterval(install,1500);
})();
