/* Entrega365 — Marketplace: busca rápida, A-Z e filtro por inicial */
(()=>{
'use strict';
let lastGrid=null, sortMode='az', activeLetter='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function grid(){return document.querySelector('#mc-grid.e365-market-grid')}
function cards(){const g=grid();return g?[...g.querySelectorAll('.e365-product')]:[]}
function title(card){return (card.querySelector('.e365-product-title')?.textContent||'').trim()}
function install(){const g=grid();if(!g||g===lastGrid&&document.getElementById('e365-market-filter'))return;if(document.getElementById('e365-market-filter'))document.getElementById('e365-market-filter').remove();lastGrid=g;
 const bar=document.createElement('section');bar.id='e365-market-filter';bar.className='e365-market-filter';bar.innerHTML=`<div class="e365-market-filter-head"><strong>🔎 Encontre seu produto</strong><span id="e365-market-count"></span></div><div class="e365-market-filter-row"><input id="e365-market-search" type="search" placeholder="Digite o nome do produto…" autocomplete="off"><select id="e365-market-sort" aria-label="Ordenar produtos"><option value="az">A → Z</option><option value="za">Z → A</option></select></div><div class="e365-market-letters" id="e365-market-letters"></div>`;
 g.parentNode.insertBefore(bar,g);
 const s=document.createElement('style');s.id='e365-market-filter-style';s.textContent=`.e365-market-filter{margin:0 0 14px;padding:14px;border:1px solid #3b3b3b;border-radius:16px;background:#1b1b1b}.e365-market-filter-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:10px}.e365-market-filter-head strong{font-size:16px}.e365-market-filter-head span{font-size:12px;color:#999}.e365-market-filter-row{display:flex;gap:8px}.e365-market-filter-row input,.e365-market-filter-row select{box-sizing:border-box;background:#121212!important;color:#fff!important;border:1px solid #444!important;border-radius:11px!important;padding:12px!important;font-size:14px!important;outline:none}.e365-market-filter-row input{flex:1;min-width:0}.e365-market-filter-row select{width:105px}.e365-market-letters{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.e365-market-letter{border:1px solid #444;background:#292929;color:#ddd;border-radius:9px;padding:7px 10px;font-weight:800;cursor:pointer}.e365-market-letter.active{background:#ffd000;color:#111;border-color:#ffd000}.e365-market-letter.all{padding-inline:12px}@media(max-width:500px){.e365-market-filter{padding:12px}.e365-market-filter-head strong{font-size:14px}.e365-market-filter-row select{width:92px}.e365-market-letter{padding:6px 8px;font-size:12px}}`;
 if(!document.getElementById('e365-market-filter-style'))document.head.appendChild(s);
 bar.querySelector('#e365-market-search').addEventListener('input',apply);bar.querySelector('#e365-market-sort').addEventListener('change',e=>{sortMode=e.target.value;apply()});
 buildLetters();apply();
}
function buildLetters(){const box=document.getElementById('e365-market-letters');if(!box)return;const letters=[...new Set(cards().map(c=>title(c).normalize('NFD').replace(/[\u0300-\u036f]/g,'').charAt(0).toUpperCase()).filter(Boolean))].sort();box.innerHTML=`<button class="e365-market-letter all active" data-letter="">Todos</button>`+letters.map(l=>`<button class="e365-market-letter" data-letter="${esc(l)}">${esc(l)}</button>`).join('');box.querySelectorAll('.e365-market-letter').forEach(b=>b.onclick=()=>{activeLetter=b.dataset.letter||'';box.querySelectorAll('.e365-market-letter').forEach(x=>x.classList.toggle('active',x===b));apply()})}
function apply(){const g=grid(),q=(document.getElementById('e365-market-search')?.value||'').trim().toLocaleLowerCase('pt-BR');if(!g)return;const all=cards();const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');all.sort((a,b)=>{const aa=normalize(title(a)),bb=normalize(title(b));return (sortMode==='za'?-1:1)*aa.localeCompare(bb,'pt-BR')});all.forEach(c=>g.appendChild(c));let visible=0;all.forEach(c=>{const t=normalize(title(c));const letter=normalize(title(c)).charAt(0).toUpperCase();const okQ=!q||t.includes(normalize(q));const okL=!activeLetter||letter===activeLetter.toLocaleLowerCase('pt-BR');c.style.display=okQ&&okL?'':'none';if(okQ&&okL)visible++});const count=document.getElementById('e365-market-count');if(count)count.textContent=`${visible} ${visible===1?'produto':'produtos'}`;let empty=g.querySelector('.e365-filter-empty');if(!empty){empty=document.createElement('div');empty.className='e365-filter-empty e365-market-empty';empty.style.gridColumn='1/-1';g.appendChild(empty)}empty.textContent=visible?'':'Nenhum produto encontrado com esse filtro.';empty.style.display=visible?'none':''}
function watch(){const g=grid();if(!g)return;const has=!!document.getElementById('e365-market-filter');if(!has)install();else if(g!==lastGrid)install()}
function boot(){const mo=new MutationObserver(()=>{clearTimeout(boot.t);boot.t=setTimeout(watch,50)});mo.observe(document.documentElement,{childList:true,subtree:true});setInterval(watch,700);watch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
