/* Entrega365 — Marketplace visual com vários produtos */
(()=>{
'use strict';
const API='/api/marketplace',ADMIN='entrega365.suporte@gmail.com';let items=[];
const getUser=()=>window.entrega365Auth?.auth?.currentUser||window.__e365Auth?.auth?.currentUser||window.__e365Auth?.currentUser||window.e365GetCurrentUser?.()||null;
async function token(){let u=getUser();if(!u?.getIdToken){await new Promise(r=>setTimeout(r,500));u=getUser()}if(!u?.getIdToken)throw new Error('Aguarde o login terminar.');return u.getIdToken()}
async function api(method='GET',body){const t=await token();const r=await fetch(API,{method,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erro HTTP ${r.status}`);return d}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function styles(){if(document.getElementById('e365-market-catalog-style'))return;const s=document.createElement('style');s.id='e365-market-catalog-style';s.textContent=`
.e365-market-wrap{padding:16px 12px 70px;max-width:1180px;margin:auto}.e365-market-hero{padding:22px 20px;border-radius:20px;background:linear-gradient(135deg,#292929,#181818);border:1px solid #3b3b3b;margin-bottom:18px}.e365-market-hero h1{margin:0;font-size:27px}.e365-market-hero p{margin:7px 0 0;color:#aaa}.e365-market-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.e365-product{overflow:hidden;background:linear-gradient(160deg,#202020,#292929);border:1px solid #3b3b3b;border-radius:18px;display:flex;flex-direction:column;min-width:0;box-shadow:0 8px 22px rgba(0,0,0,.25)}.e365-product-img{aspect-ratio:1/1;background:#111;display:grid;place-items:center;overflow:hidden}.e365-product-img img{width:100%;height:100%;object-fit:cover;display:block}.e365-product-noimg{font-size:46px;opacity:.65}.e365-product-body{padding:14px;display:flex;flex-direction:column;gap:7px;flex:1}.e365-product-title{font-size:16px;font-weight:950}.e365-product-desc{font-size:12px;color:#aaa;line-height:1.45;min-height:34px}.e365-product-btn{margin-top:auto;display:block;text-align:center;padding:12px;border-radius:11px;background:#ffd000;color:#111;text-decoration:none;font-weight:950}.e365-market-admin{padding:16px;border:1px solid #3b3b3b;background:#1b1b1b;border-radius:18px;margin-bottom:18px}.e365-market-admin h3{margin:0 0 5px}.e365-market-admin p{margin:0 0 12px;color:#999;font-size:12px}.e365-market-form{display:grid;grid-template-columns:1fr 1fr;gap:9px}.e365-market-form input{background:#121212!important;color:#fff!important;border:1px solid #444!important;border-radius:10px!important;padding:11px!important}.e365-market-form .wide{grid-column:1/-1}.e365-market-actions{display:flex;gap:8px;margin-top:10px}.e365-market-actions button{flex:1;padding:12px;border-radius:11px;font-weight:900;cursor:pointer}.e365-market-add{background:#ffd000;color:#111}.e365-market-save{background:#2c2c2c;color:#fff;border:1px solid #555}.e365-market-list{display:grid;gap:8px;margin-top:14px}.e365-market-row{display:flex;align-items:center;gap:10px;padding:9px;background:#242424;border-radius:10px}.e365-market-row img{width:44px;height:44px;object-fit:cover;border-radius:8px;background:#111}.e365-market-row span{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.e365-market-remove{background:#3a1d1d!important;color:#ff6b60!important;border:1px solid #663333!important;flex:0 0 auto!important}.e365-market-status{font-size:12px;color:#aaa;margin-top:8px}.e365-market-empty{text-align:center;padding:45px 15px;color:#999;background:#1a1a1a;border:1px dashed #444;border-radius:18px}
@media(max-width:1000px){.e365-market-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.e365-market-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.e365-market-hero{padding:18px}.e365-market-hero h1{font-size:22px}.e365-product-body{padding:11px}.e365-product-title{font-size:14px}.e365-product-desc{font-size:11px}.e365-product-btn{padding:10px;font-size:12px}.e365-market-form{grid-template-columns:1fr}.e365-market-form .wide{grid-column:auto}}@media(max-width:390px){.e365-market-grid{grid-template-columns:1fr}.e365-product-img{aspect-ratio:1.25/1}}
`;document.head.appendChild(s)}
function root(){return document.querySelector('.cm-overlay #cm-content')||document.querySelector('#cm-content')}
function setActive(){document.querySelectorAll('.cm-tab').forEach(x=>x.classList.toggle('active',x.dataset.v==='marketplace'))}
function render(){const c=root();if(!c)return false;setActive();const u=getUser(),isAdmin=(u?.email||'').toLowerCase()===ADMIN;c.innerHTML=`<div class="e365-market-wrap"><section class="e365-market-hero"><h1>🛍️ Marketplace Entrega365</h1><p>Produtos e oportunidades selecionados para facilitar o dia a dia do entregador.</p></section>${isAdmin?`<section class="e365-market-admin"><h3>⚙️ Gerenciar produtos</h3><p>Adicione quantos produtos quiser. Cada produto pode ter sua própria foto e link.</p><div class="e365-market-form"><input id="mc-title" placeholder="Nome do produto"><input id="mc-image" placeholder="URL da foto"><input id="mc-link" class="wide" placeholder="URL do produto / loja"><input id="mc-desc" class="wide" placeholder="Descrição curta (opcional)"></div><div class="e365-market-actions"><button class="e365-market-add" id="mc-add">＋ ADICIONAR PRODUTO</button><button class="e365-market-save" id="mc-save">💾 SALVAR CATÁLOGO</button></div><div class="e365-market-status" id="mc-status"></div><div class="e365-market-list" id="mc-list"></div></section>`:''}<section id="mc-grid" class="e365-market-grid"><div class="e365-market-empty">Carregando produtos…</div></section></div>`;if(isAdmin){document.getElementById('mc-add').onclick=add;document.getElementById('mc-save').onclick=save;adminList()}return true}
function drawGrid(){const g=document.getElementById('mc-grid');if(!g)return;if(!items.length){g.innerHTML='<div class="e365-market-empty" style="grid-column:1/-1">Nenhum produto cadastrado ainda.</div>';return}g.innerHTML=items.map(x=>`<article class="e365-product"><div class="e365-product-img">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="${esc(x.title)}" loading="lazy" onerror="this.style.display='none';this.parentElement.innerHTML='<div class=\'e365-product-noimg\'>🛍️</div>'">`:'<div class="e365-product-noimg">🛍️</div>'}</div><div class="e365-product-body"><div class="e365-product-title">${esc(x.title)}</div><div class="e365-product-desc">${esc(x.description||'Confira este produto.')}</div><a class="e365-product-btn" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">🛒 VER PRODUTO</a></div></article>`).join('')}
function adminList(){const l=document.getElementById('mc-list');if(!l)return;l.innerHTML=items.map((x,i)=>`<div class="e365-market-row">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="">`:'<span style="flex:0 0 auto">🛍️</span>'}<span>${esc(x.title)}</span><button class="e365-market-remove" data-i="${i}">EXCLUIR</button></div>`).join('');l.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{items.splice(Number(b.dataset.i),1);adminList();drawGrid()})}
function add(){if(items.length>=100){alert('Limite de 100 produtos atingido.');return}const title=document.getElementById('mc-title').value.trim(),imageUrl=document.getElementById('mc-image').value.trim(),link=document.getElementById('mc-link').value.trim(),description=document.getElementById('mc-desc').value.trim();if(!title||!link){alert('Informe o nome e o link do produto.');return}try{new URL(link);if(imageUrl)new URL(imageUrl)}catch{alert('Confira as URLs informadas.');return}items.push({id:crypto.randomUUID?.()||String(Date.now()),title,description,imageUrl,link});['mc-title','mc-image','mc-link','mc-desc'].forEach(id=>document.getElementById(id).value='');adminList();drawGrid()}
async function save(){const s=document.getElementById('mc-status');s.textContent='Salvando…';try{const d=await api('PUT',{items,affiliateUrl:items[0]?.link||''});items=d.items||items;s.textContent=`Catálogo salvo: ${items.length} produto(s).`;drawGrid();adminList()}catch(e){s.textContent='Erro: '+e.message}}
async function load(){try{const d=await api('GET');items=Array.isArray(d.items)?d.items:[];drawGrid();adminList()}catch(e){const g=document.getElementById('mc-grid');if(g)g.innerHTML=`<div class="e365-market-empty" style="grid-column:1/-1">Não foi possível carregar o Marketplace.<br>${esc(e.message)}</div>`}}
function openCatalog(){styles();if(!render())return;load()}
function intercept(e){const b=e.target.closest?.('.cm-tab[data-v="marketplace"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();setTimeout(openCatalog,0)}
function watch(){const b=document.querySelector('.cm-tab[data-v="marketplace"].active');if(b&&root()&&!root().querySelector('.e365-market-wrap'))openCatalog()}
function boot(){styles();document.addEventListener('click',intercept,true);new MutationObserver(watch).observe(document.documentElement,{childList:true,subtree:true});setInterval(watch,1000);watch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
