(function(){
  'use strict';
  if (window.__deliveryProfilesLoaded) return;
  window.__deliveryProfilesLoaded = true;
  const style=document.createElement('style');style.textContent='#companyProfileBar{padding:12px;margin-bottom:12px;background:linear-gradient(145deg,#0d1926,#09121d);border:1px solid #1b2a3b;border-radius:18px}.company-profile-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.company-kicker{font-size:10px;color:#91a0b4;font-weight:800;letter-spacing:.7px}.company-title{font-size:17px;font-weight:900;margin-top:3px}.company-add{width:38px;height:38px;border-radius:12px;border:1px solid #24547f;background:#081522;color:#49a8ff;font-size:22px}.company-controls{display:grid;grid-template-columns:1fr 42px 42px;gap:7px;margin-top:10px}.company-controls select{background:#08121e;color:#fff;border:1px solid #223448;border-radius:10px;padding:10px}.company-action{border:1px solid #223448;background:#08121e;color:#dbe7f4;border-radius:10px}.company-hint{font-size:10px;color:#91a0b4;margin-top:8px}.latest-worked-card{border-color:#155ba0;background:linear-gradient(145deg,#0b1d31,#071522)}.latest-badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#073a25;color:#42ef9c;font-weight:900;font-size:10px}.latest-date{font-size:18px;font-weight:900;margin:9px 0 12px;text-transform:capitalize}.latest-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.latest-grid div{padding:10px;border:1px solid #1b2a3b;border-radius:12px;background:#081522}.latest-grid span{display:block;color:#91a0b4;font-size:10px}.latest-grid b{display:block;margin-top:4px;font-size:15px;color:#fff}@media(max-width:390px){.company-controls{grid-template-columns:1fr 38px 38px}.latest-grid{gap:6px}.latest-grid div{padding:9px}}';document.head.appendChild(style);
  const KEY='dcv2:';const baseUser=user;const metaKey=KEY+'profiles:'+baseUser;const activeKey=KEY+'activeProfile:'+baseUser;
  function readMeta(){try{return JSON.parse(localStorage.getItem(metaKey))||{profiles:[{id:'default',name:'Principal'}]}}catch(e){return{profiles:[{id:'default',name:'Principal'}]}}}
  function writeMeta(m){localStorage.setItem(metaKey,JSON.stringify(m))}
  let meta=readMeta();if(!Array.isArray(meta.profiles)||!meta.profiles.length)meta={profiles:[{id:'default',name:'Principal'}]};if(!meta.profiles.some(p=>p.id==='default'))meta.profiles.unshift({id:'default',name:'Principal'});writeMeta(meta);
  let active=localStorage.getItem(activeKey)||'default';if(!meta.profiles.some(p=>p.id===active))active='default';if(active!=='default'&&user===baseUser)user=baseUser+'::empresa::'+active;
  function profileName(){const p=meta.profiles.find(x=>x.id===active)||meta.profiles[0];return p.name}window.__deliveryProfile={baseUser:baseUser,active:active,name:profileName};
  function esc(s){return String(s||'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
  function switchProfile(id){if(!meta.profiles.some(p=>p.id===id))return;localStorage.setItem(activeKey,id);location.reload()}
  function addProfile(){const name=prompt('Nome da empresa:');if(!name||!name.trim())return;const id='p_'+Date.now().toString(36);meta.profiles.push({id:id,name:name.trim()});writeMeta(meta);localStorage.setItem(activeKey,id);location.reload()}
  function renameProfile(){const p=meta.profiles.find(x=>x.id===active);if(!p)return;const name=prompt('Novo nome da empresa:',p.name);if(!name||!name.trim())return;p.name=name.trim();writeMeta(meta);location.reload()}
  function deleteProfile(){if(active==='default')return alert('O perfil Principal não pode ser excluído.');const p=meta.profiles.find(x=>x.id===active);if(!p)return;if(!confirm('Excluir o perfil “'+p.name+'”?'))return;meta.profiles=meta.profiles.filter(x=>x.id!==active);writeMeta(meta);localStorage.setItem(activeKey,'default');location.reload()}
  function updateHeader(){const sub=document.querySelector('.head .sub');if(sub)sub.textContent=profileName()}
  function mountProfileBar(){const main=document.querySelector('main');if(!main)return;updateHeader();let bar=document.getElementById('companyProfileBar');if(bar)return;bar=document.createElement('section');bar.id='companyProfileBar';bar.className='card company-profile-bar';bar.innerHTML='<div class="company-profile-head"><div><div class="company-kicker">EMPRESA ATIVA</div><div class="company-title">🏢 '+esc(profileName())+'</div></div><button id="companyAdd" class="company-add">＋</button></div><div class="company-controls"><select id="companySelect" aria-label="Selecionar empresa">'+meta.profiles.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===active?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select><button id="companyRename" class="company-action">✎</button><button id="companyDelete" class="company-action">🗑</button></div><div class="company-hint">Lançamentos, taxas, KM, gastos e mecânica ficam separados por empresa.</div>';main.prepend(bar);bar.querySelector('#companySelect').onchange=e=>switchProfile(e.target.value);bar.querySelector('#companyAdd').onclick=addProfile;bar.querySelector('#companyRename').onclick=renameProfile;bar.querySelector('#companyDelete').onclick=deleteProfile}
  function latestWorkedDays(){const prefix=KEY+user+':day:';const arr=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!k.startsWith(prefix))continue;try{const d=JSON.parse(localStorage.getItem(k));const date=k.slice(prefix.length);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))continue;const worked=(Array.isArray(d.entries)&&d.entries.length)||Number(d.arrancada)>0||d.kmInicial!==''||d.kmFinal!=='';if(worked)arr.push({date:date,d:d})}catch(e){}}return arr.sort((a,b)=>b.date.localeCompare(a.date))}
  function money(n){return(Number(n)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
  function monthLatestCard(){if(view!=='month')return;const main=document.querySelector('main');if(!main||document.getElementById('latestWorkedCard'))return;const days=latestWorkedDays();if(!days.length)return;const x=days[0],d=x.d,entries=Array.isArray(d.entries)?d.entries:[],taxas=entries.reduce((s,e)=>s+(Number(e.taxa)||0),0),total=taxas+(Number(d.arrancada)||0),km=Math.max(0,(Number(d.kmFinal)||0)-(Number(d.kmInicial)||0)),label=new Date(x.date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});const card=document.createElement('section');card.id='latestWorkedCard';card.className='card latest-worked-card';card.innerHTML='<div class="latest-badge">ÚLTIMO DIA TRABALHADO</div><div class="latest-date">'+esc(label)+'</div><div class="latest-grid"><div><span>Comandas</span><b>'+entries.length+'</b></div><div><span>Taxas</span><b>'+money(taxas)+'</b></div><div><span>KM rodados</span><b>'+km+' km</b></div><div><span>Total do dia</span><b>'+money(total)+'</b></div></div>';main.insertBefore(card,main.children[1]||null)}
  function mount(){mountProfileBar();monthLatestCard()}
  if(typeof shell==='function'){const oldShell=shell;shell=function(content){oldShell(content);setTimeout(mount,0)}}
  if(typeof go==='function'){const oldGo=go;go=function(v){oldGo(v);setTimeout(mount,0)}}
  if(active!=='default'&&typeof render==='function')setTimeout(()=>render(),0);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,20));else setTimeout(mount,20);
})();
