(()=>{
'use strict';
const ST={trans:{name:'Transamérica 99,7 FM',freq:'99,7 FM · Balneário Camboriú / SC',url:'https://www.trans99fm.com.br/'},rock:{name:'89 FM A Rádio Rock',freq:'89,1 FM · São Paulo / SP',url:'https://radiomixer.net/pt/bra/arock'}};
let current=localStorage.getItem('dc-radio')||'trans';
const main=()=>document.querySelector('#app main');
const nav=()=>document.querySelector('#app .tabs');
function ensureTab(){const n=nav();if(!n||n.querySelector('.radio-tab'))return;const b=document.createElement('button');b.type='button';b.className='tab radio-tab';b.innerHTML='<b>📻</b>Rádio';b.onclick=openRadio;n.appendChild(b)}
function openRadio(){const m=main();if(!m)return;document.querySelectorAll('#app .tab').forEach(x=>x.classList.remove('active'));m.className='';m.innerHTML='<section class="radio-screen-fix"><div class="rf-head"><div class="rf-icon">📻</div><div><h1>Rádio</h1><p>Ouça enquanto trabalha</p></div></div><div class="rf-player"><div class="rf-status">ESCOLHA UMA RÁDIO</div><h2 id="rfName"></h2><div id="rfFreq" class="rf-freq"></div><button id="rfPlay" class="rf-play">▶ Ouvir rádio</button></div><div class="rf-label">RÁDIOS</div><div id="rfStations"></div><div id="rfSource"></div></section>';document.querySelector('.radio-tab')?.classList.add('active');renderStations();select(current)}
function renderStations(){const box=document.getElementById('rfStations');if(!box)return;box.innerHTML=Object.entries(ST).map(([id,s])=>'<button type="button" class="rf-station '+(id===current?'active':'')+'" data-rf="'+id+'"><span class="rf-station-icon">'+(id==='rock'?'🎸':'📻')+'</span><span><strong>'+s.name+'</strong><small>'+s.freq+'</small></span><b>›</b></button>').join('');box.querySelectorAll('[data-rf]').forEach(b=>b.onclick=()=>select(b.dataset.rf))}
function select(id){current=id;localStorage.setItem('dc-radio',id);const s=ST[id],n=document.getElementById('rfName'),f=document.getElementById('rfFreq'),p=document.getElementById('rfPlay');if(!n)return;n.textContent=s.name;f.textContent=s.freq;document.querySelectorAll('.rf-station').forEach(x=>x.classList.toggle('active',x.dataset.rf===id));p.textContent='▶ Ouvir rádio';p.onclick=()=>play(s)}
function play(s){const source=document.getElementById('rfSource');if(!source)return;source.innerHTML='<div class="rf-embed"><iframe src="'+s.url+'" title="'+s.name+'" allow="autoplay; encrypted-media; picture-in-picture" loading="eager"></iframe></div><a class="rf-link" href="'+s.url+'" target="_blank" rel="noopener">Abrir transmissão</a>';document.querySelector('.rf-status').textContent='PLAYER ABERTO';document.getElementById('rfPlay').textContent='⏸ Player aberto'}
if(!document.getElementById('radio-fix-style')){const style=document.createElement('style');style.id='radio-fix-style';style.textContent='.radio-screen-fix{padding-bottom:20px}.rf-head{display:flex;align-items:center;gap:12px;margin-bottom:14px}.rf-icon{width:58px;height:58px;border-radius:17px;background:#ffc52d;color:#111827;display:grid;place-items:center;font-size:29px}.rf-head h1{margin:0;font-size:25px}.rf-head p{margin:3px 0;color:#91a0b4;font-size:13px}.rf-player{background:linear-gradient(145deg,#182238,#111a2b);border-radius:22px;padding:18px;margin-bottom:18px}.rf-status{font-size:12px;font-weight:900;color:#ffd044}.rf-player h2{font-size:23px;margin:12px 0 3px}.rf-freq{color:#b8c2d0;font-size:14px}.rf-play{width:100%;height:58px;border:0;border-radius:16px;background:#ffd447;color:#121a28;font-size:18px;font-weight:900;margin-top:20px}.rf-label{font-size:12px;font-weight:900;color:#91a0b4;margin:18px 4px 8px}.rf-station{width:100%;display:flex;align-items:center;gap:12px;text-align:left;background:#0b1522;color:#fff;border:1px solid #1c2c40;border-radius:17px;padding:13px;margin:8px 0}.rf-station.active{border-color:#ffd447;background:#141c29}.rf-station-icon{width:48px;height:48px;border-radius:14px;background:#eef2f7;display:grid;place-items:center;font-size:24px;flex:0 0 auto}.rf-station span:nth-child(2){min-width:0;flex:1}.rf-station strong,.rf-station small{display:block}.rf-station small{color:#91a0b4;margin-top:4px}.rf-station>b{font-size:28px;color:#94a5b8}.rf-embed{margin-top:14px;border-radius:16px;overflow:hidden;background:#fff;border:1px solid #263a50}.rf-embed iframe{width:100%;height:430px;border:0;display:block}.rf-link{display:block;margin-top:10px;padding:12px;border-radius:12px;background:#0a1725;border:1px solid #2b4560;color:#dce7f3;text-align:center;text-decoration:none;font-weight:800}@media(max-width:600px){.rf-embed iframe{height:390px}}';document.head.appendChild(style)}
function boot(){ensureTab()}
window.addEventListener('load',boot);setTimeout(boot,200);setTimeout(boot,800);setTimeout(boot,1600);
})();