(()=>{
'use strict';
const ST={
 trans:{name:'Transamérica 99,7 FM',freq:'99,7 FM · Balneário Camboriú / SC',page:'https://www.radios.com.br/aovivo/radio-transamerica-997-fm/14885'},
 rock:{name:'89 FM A Rádio Rock',freq:'89,1 FM · São Paulo / SP',stream:'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_89FM_ADP_SC'}
};
let current=localStorage.getItem('dc-radio')||'trans', audio=null;
function main(){return document.querySelector('#app main')}
function nav(){return document.querySelector('#app .tabs')}
function ensureTab(){const n=nav();if(!n||n.querySelector('.radio-tab'))return;const b=document.createElement('button');b.type='button';b.className='tab radio-tab';b.innerHTML='<b>📻</b>Rádio';b.addEventListener('click',openRadio);n.appendChild(b)}
function openRadio(){const m=main();if(!m)return;document.querySelectorAll('#app .tab').forEach(x=>x.classList.remove('active'));m.innerHTML=`<section class="radio-screen-fix"><div class="rf-head"><div class="rf-icon">📻</div><div><h1>Rádio</h1><p>Ouça enquanto trabalha</p></div></div><div class="rf-player"><div id="rfStatus" class="rf-status">ESCOLHA UMA RÁDIO</div><h2 id="rfName"></h2><div id="rfFreq" class="rf-freq"></div><div id="rfControls"></div></div><div class="rf-label">RÁDIOS</div><div id="rfStations"></div></section>`;document.querySelector('.radio-tab')?.classList.add('active');renderStations();select(current,false)}
function renderStations(){const box=document.getElementById('rfStations');if(!box)return;box.innerHTML=Object.entries(ST).map(([id,s])=>`<button type="button" class="rf-station ${id===current?'active':''}" data-rf="${id}"><span class="rf-station-icon">${id==='rock'?'🎸':'📻'}</span><span><strong>${s.name}</strong><small>${s.freq}</small></span><b>›</b></button>`).join('');box.querySelectorAll('[data-rf]').forEach(b=>b.onclick=()=>select(b.dataset.rf,true))}
function select(id,playNow){current=id;localStorage.setItem('dc-radio',id);const s=ST[id],n=document.getElementById('rfName'),f=document.getElementById('rfFreq'),c=document.getElementById('rfControls');if(!n)return;if(audio){audio.pause();audio.src='';audio=null}n.textContent=s.name;f.textContent=s.freq;document.querySelectorAll('.rf-station').forEach(x=>x.classList.toggle('active',x.dataset.rf===id));if(id==='rock'){c.innerHTML='<button id="rfPlay" class="rf-play">▶ Tocar 89 FM</button><div class="rf-note">Transmissão direta no aplicativo</div>';document.getElementById('rfPlay').onclick=()=>playRock(s)}else{c.innerHTML=`<a class="rf-play rf-linkbtn" href="${s.page}" target="_blank" rel="noopener">▶ Ouvir Transamérica</a><div class="rf-note">A emissora disponibiliza o player por página externa.</div>`}if(playNow&&id==='rock')playRock(s)}
function playRock(s){if(audio){audio.pause();audio.src='';}audio=new Audio(s.stream);audio.preload='none';audio.autoplay=true;audio.volume=.9;const st=document.getElementById('rfStatus'),btn=document.getElementById('rfPlay');if(st)st.textContent='CONECTANDO…';if(btn)btn.textContent='⏸ Parar';audio.play().then(()=>{if(st)st.textContent='TOCANDO AGORA'}).catch(()=>{if(st)st.textContent='Não foi possível iniciar automaticamente';if(btn)btn.textContent='▶ Tocar 89 FM'});if(btn)btn.onclick=()=>{if(!audio)return;if(audio.paused){audio.play();btn.textContent='⏸ Parar'}else{audio.pause();btn.textContent='▶ Tocar 89 FM';if(st)st.textContent='PAUSADO'}}}
const style=document.createElement('style');style.textContent=`.radio-screen-fix{padding-bottom:20px}.rf-head{display:flex;align-items:center;gap:12px;margin-bottom:14px}.rf-icon{width:58px;height:58px;border-radius:17px;background:#ffc52d;color:#111827;display:grid;place-items:center;font-size:29px}.rf-head h1{margin:0;font-size:25px}.rf-head p{margin:3px 0;color:#91a0b4;font-size:13px}.rf-player{background:linear-gradient(145deg,#182238,#111a2b);border-radius:22px;padding:18px;margin-bottom:18px}.rf-status{font-size:12px;font-weight:900;color:#ffd044}.rf-player h2{font-size:23px;margin:12px 0 3px}.rf-freq{color:#b8c2d0;font-size:14px}.rf-play{display:flex;width:100%;height:58px;border:0;border-radius:16px;background:#ffd447;color:#121a28;font-size:18px;font-weight:900;margin-top:20px;align-items:center;justify-content:center;text-decoration:none}.rf-note{font-size:11px;color:#91a0b4;text-align:center;margin-top:10px}.rf-label{font-size:12px;font-weight:900;color:#91a0b4;margin:18px 4px 8px}.rf-station{width:100%;display:flex;align-items:center;gap:12px;text-align:left;background:#0b1522;color:#fff;border:1px solid #1c2c40;border-radius:17px;padding:13px;margin:8px 0}.rf-station.active{border-color:#ffd447;background:#141c29}.rf-station-icon{width:48px;height:48px;border-radius:14px;background:#eef2f7;display:grid;place-items:center;font-size:24px;flex:0 0 auto}.rf-station span:nth-child(2){min-width:0;flex:1}.rf-station strong,.rf-station small{display:block}.rf-station small{color:#91a0b4;margin-top:4px}.rf-station>b{font-size:28px;color:#94a5b8}.rf-linkbtn{box-sizing:border-box}@media(max-width:600px){.rf-player{padding:16px}}`;document.head.appendChild(style);
function boot(){ensureTab()}
window.addEventListener('load',boot);setTimeout(boot,100);setTimeout(boot,500);setTimeout(boot,1500);
})();