/* Entrega365 — sincronização robusta entre navegadores (UID + proteção por volume de dados) */
import { getFirestore, doc, getDoc, setDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-firestore.js";
import { getApp } from "https://www.gstatic.com/firebasejs/12.9.0/firebase-app.js";

const DB=getFirestore(getApp()), ROOT="entrega365Sync";
let uid="", ref=null, busy=false, unsub=null, timer=0, started=false;
const stateKey=()=>`entrega365:syncBridge:${uid}`;
const state=()=>{try{return JSON.parse(localStorage.getItem(stateKey())||"{}")}catch{return{}}};
const saveState=x=>localStorage.setItem(stateKey(),JSON.stringify({...state(),...x}));
const currentUid=()=>window.entrega365Auth?.auth?.currentUser?.uid||((localStorage.getItem("dcv2:session")||"").startsWith("google:")?(localStorage.getItem("dcv2:session")||"").slice(7):"");
const session=()=>localStorage.getItem("dcv2:session")||"";
const included=k=>{const s=session(),pre="dcv2:"+s+":";return !!k&&(k.startsWith(pre)||k===`entrega365:establishments:${s}`||k===`entrega365:currentEstablishment:${s}`||["entrega365:agenda","entrega365:settings","e365month"].includes(k));};
function snapshot(){const out={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&included(k))out[k]=localStorage.getItem(k)}return out;}
function stats(data){let keys=0,days=0,entries=0,expenses=0,score=0;for(const [k,v] of Object.entries(data||{})){keys++;score+=Math.min(10000,String(v||"").length);if(k.includes(":day:")){days++;try{const d=JSON.parse(v);entries+=Array.isArray(d?.entries)?d.entries.length:0;score+=entries*1000+(d?.arrancada?50:0)+(d?.kmInicial?20:0)+(d?.kmFinal?20:0)}catch{score+=10}}if(k.includes(":exp:")){try{expenses+=Array.isArray(JSON.parse(v)?.items)?JSON.parse(v).items.length:0}catch{expenses++}}}return{keys,days,entries,expenses,score};}
function hasData(s){return s.keys>0&&(s.entries>0||s.expenses>0||s.days>0||s.score>100);}
function localInfo(){const data=snapshot();return{data,stats:stats(data)};}
function apply(data){const before=localInfo();const keys=Object.keys(before.data);keys.forEach(k=>localStorage.removeItem(k));for(const[k,v]of Object.entries(data||{}))if(included(k))localStorage.setItem(k,v);if(session())localStorage.setItem("dcv2:session",session());window.dispatchEvent(new Event("e365-sync-bridge-restored"));window.dispatchEvent(new Event("e365-data-changed"));setTimeout(()=>window.render?.(),0);}
async function push(local,remoteAt=0){if(busy||!uid||!ref)return false;const ls=local?.stats||stats(local?.data||{});if(!hasData(ls))return false;busy=true;try{const snap=await getDoc(ref),remote=snap.exists()?snap.data()||{}:{},rs=stats(remote.data||{});if(hasData(rs)&&rs.score>ls.score*1.02){saveState({remoteAt:Number(remote.updatedAt||remoteAt||0),remoteNewer:true,dirty:false,lastAction:"protected-local"});return false;}const at=Date.now();await setDoc(ref,{version:220,uid,data:local.data,stats:ls,updatedAt:at},{merge:false});saveState({remoteAt:at,savedAt:at,lastStats:ls,dirty:false,lastAction:"push"});return true;}catch(e){saveState({error:String(e?.message||e)});return false}finally{busy=false;}}
async function reconcile(reason="auto"){const u=currentUid();if(!u)return false;if(uid!==u){if(unsub){unsub();unsub=null}uid=u;ref=doc(DB,ROOT,uid);started=false;}if(busy)return false;const local=localInfo();try{const snap=await getDoc(ref);const remote=snap.exists()?snap.data()||{}:null;const rs=stats(remote?.data||{});const ls=local.stats;const ra=Number(remote?.updatedAt||0);if(!remote?.data||!hasData(rs)){if(hasData(ls))return await push(local,ra);return false;}if(rs.score>ls.score*1.02){apply(remote.data);saveState({remoteAt:ra,lastStats:rs,lastAction:"restore",dirty:false});return true;}if(ls.score>rs.score*1.02){return await push(local,ra);}const st=state();if(ra>Number(st.remoteAt||0)&&!st.dirty){apply(remote.data);saveState({remoteAt:ra,lastStats:rs,lastAction:"restore-equal",dirty:false});return true;}if(hasData(ls)&&ra>0)return await push(local,ra);return false;}catch(e){saveState({error:String(e?.message||e)});return false;}}
function queue(){if(!uid)return;clearTimeout(timer);saveState({dirty:true,changedAt:Date.now()});timer=setTimeout(()=>reconcile("change"),1200);}
async function start(){if(started&&uid===currentUid())return true;const u=currentUid();if(!u){setTimeout(start,1000);return false;}uid=u;ref=doc(DB,ROOT,uid);started=true;await reconcile("start");if(unsub)unsub();unsub=onSnapshot(ref,s=>{if(!s.exists()||busy)return;const remote=s.data()||{},ra=Number(remote.updatedAt||0),st=state();if(ra>Number(st.remoteAt||0)&&!st.dirty)reconcile("remote");},e=>saveState({error:String(e?.message||e)}));return true;}
window.e365SyncBridge={start,reconcile,save:()=>reconcile("manual"),status:()=>({uid,busy,state:state(),local:localInfo().stats})};
window.addEventListener("e365-data-changed",queue);window.addEventListener("online",()=>start().catch(()=>{}));window.addEventListener("focus",()=>reconcile("focus").catch(()=>{}));window.addEventListener("pageshow",()=>reconcile("pageshow").catch(()=>{}));
setTimeout(start,500);setInterval(()=>reconcile("interval").catch(()=>{}),5000);
