const E365P="dcv2:";
function e365User(){return localStorage.getItem(E365P+"session")||"usuario"}
function e365Keys(){const p=E365P+e365User()+":";return Object.keys(localStorage).filter(k=>k.startsWith(p))}
function e365Val(k){try{return JSON.parse(localStorage.getItem(k))}catch{return localStorage.getItem(k)}}
function e365Download(name,text,type){const b=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.e365Backup=function(){const data={app:"Entrega365",version:12,user:e365User(),createdAt:new Date().toISOString(),data:{}};e365Keys().forEach(k=>data.data[k]=e365Val(k));e365Download("entrega365-backup-"+new Date().toISOString().slice(0,10)+".json",JSON.stringify(data,null,2),"application/json;charset=utf-8")};
window.backup=window.e365Backup;
window.e365Restore=function(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result),data=o.data||o;if(!data||typeof data!=="object")throw Error("Formato inválido");if(!confirm("Restaurar este backup neste usuário? Os dados atuais serão substituídos."))return;const u=e365User(),prefix=E365P+u+":";e365Keys().forEach(k=>localStorage.removeItem(k));Object.keys(data).forEach(k=>{let nk=k;if(o.user&&k.startsWith(E365P+o.user+":"))nk=prefix+k.slice((E365P+o.user+":").length);else if(!k.startsWith(prefix))return;if(nk===E365P+"session"||nk===E365P+"users"||nk.endsWith(":session"))return;localStorage.setItem(nk,typeof data[k]==="string"?data[k]:JSON.stringify(data[k]))});alert("Backup restaurado com sucesso. O aplicativo será recarregado.");location.reload()}catch(e){alert("Erro ao restaurar: "+e.message)}};r.readAsText(file)};
function e365CsvCell(v){return '"'+String(v??"").replace(/"/g,'""')+'"'}
window.e365CSV=function(){const rows=[["Tipo","Data","Comanda","Taxa","OK","KM inicial","KM final","Arrancada","Valor","Descrição","Categoria"]];e365Keys().forEach(k=>{const p=E365P+e365User()+":",s=k.slice(p.length),d=e365Val(k)||{};if(s.startsWith("day:")){const date=s.slice(4);(d.entries||[]).forEach(e=>rows.push(["Comanda",date,e.comanda||"",e.taxa||0,e.ok?"SIM":"NÃO",d.kmInicial||"",d.kmFinal||"",d.arrancada||0,"","",""]))}else if(s.startsWith("exp:")){const date=s.slice(4);(d.items||[]).forEach(e=>rows.push(["Gasto",date,"","","","","","",e.val||e.valor||0,e.desc||e.descricao||e.nome||"",e.cat||e.categoria||""]))}else if(s==="mechanica"){rows.push(["Mecânica","","","","","","",d.ultimaTroca||"",d.motoKm||"",d.intervalo||"",""])}});e365Download("entrega365-planilha-"+new Date().toISOString().slice(0,10)+".csv","\ufeff"+rows.map(r=>r.map(e365CsvCell).join(";")).join("\r\n"),"text/csv;charset=utf-8")};
window.e365PDF=function(){const w=window.open("","_blank");if(!w){alert("Permita pop-ups para gerar o PDF.");return}const u=e365User(),p=E365P+u+":",rows=[];e365Keys().forEach(k=>{const s=k.slice(p.length),d=e365Val(k)||{};if(s.startsWith("day:")){const date=s.slice(4);rows.push("<h2>Dia "+date+"</h2><p>KM inicial: "+(d.kmInicial||"-")+" | KM final: "+(d.kmFinal||"-")+" | Arrancada: R$ "+Number(d.arrancada||0).toFixed(2)+"</p>");(d.entries||[]).forEach(e=>rows.push("<p>Comanda: <b>"+(e.comanda||"")+"</b> | Taxa: R$ "+Number(e.taxa||0).toFixed(2)+" | OK: "+(e.ok?"SIM":"NÃO")+"</p>"))}else if(s.startsWith("exp:")){(d.items||[]).forEach(e=>rows.push("<p>Gasto "+s.slice(4)+": "+(e.desc||e.descricao||e.nome||"")+" — R$ "+Number(e.val||e.valor||0).toFixed(2)+"</p>"))}});w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Entrega365</title><style>body{font:14px Arial;padding:24px;color:#111}h1{border-bottom:3px solid #ffd000;padding-bottom:8px}h2{margin-top:22px;border-bottom:1px solid #ccc;padding-bottom:5px}</style></head><body><h1>Entrega365</h1><p>Relatório de '+u+' — '+new Date().toLocaleString("pt-BR")+'</p>'+(rows.join("")||"<p>Nenhum dado encontrado.</p>")+'<script>setTimeout(function(){print()},400)<\/script></body></html>');w.document.close()};
function e365Fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.();return}document.documentElement.requestFullscreen?.().catch(()=>{})}
window.e365Fullscreen=e365Fullscreen;
function e365InstallTools(){const main=document.querySelector("main");if(!main)return;if(!document.getElementById("e365-tools")){const box=document.createElement("div");box.id="e365-tools";box.innerHTML='<button class="e365-backup" onclick="e365Backup()">⬇ Backup</button><button onclick="document.getElementById(\'e365RestoreFile\').click()">⬆ Subir</button><button class="e365-plan" onclick="e365CSV()">▦ Planilha</button><button onclick="e365PDF()">PDF</button><input id="e365RestoreFile" type="file" accept="application/json,.json" hidden onchange="e365Restore(this.files[0])">';main.prepend(box)}const actions=document.querySelector(".actions");if(actions&&!document.getElementById("e365-fullscreen")){const b=document.createElement("button");b.id="e365-fullscreen";b.className="ico";b.type="button";b.title="Tela cheia";b.textContent="⛶";b.onclick=e365Fullscreen;actions.prepend(b)}if(!document.getElementById("e365-tools-style")){const s=document.createElement("style");s.id="e365-tools-style";s.textContent='#e365-tools{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:0 0 12px;padding:9px;background:#202020;border:1px solid #444;border-radius:15px;box-shadow:0 8px 25px #0004}#e365-tools button{min-height:42px;border:1px solid #555;border-radius:10px;background:#292929;color:#fff;font-weight:900;font-size:12px}#e365-tools .e365-backup{background:#ffd000;color:#151515;border-color:#ffd000}#e365-tools .e365-plan{color:#ffd000}@media(max-width:390px){#e365-tools{gap:5px;padding:7px}#e365-tools button{font-size:10px;padding:5px}}';document.head.appendChild(s)}}
new MutationObserver(e365InstallTools).observe(document.documentElement,{childList:true,subtree:true});setTimeout(e365InstallTools,100);setInterval(e365InstallTools,800);
